In [4]:
import pandas as pd

In [5]:
import json

data = []
with open('News_Category_Dataset_v3.json', 'r') as f:
    for line in f:
        try:
            data.append(json.loads(line))
        except json.JSONDecodeError as e:
            print(f"Skipping malformed JSON line: {line.strip()} - Error: {e}")
df = pd.DataFrame(data)

Skipping malformed JSON line: {"category": "GREEN", "headline": "Elon Musk Floats Solar Overhaul Of Puerto Rico Power Grid, Governor Says 'Let's Talk'", "authors": "Carla Herreria", "link": "https://www.huffingtonpost.com/entry/elon-musk-rebuild-puerto-rico-power-grid-s - Error: Unterminated string starting at: line 1 column 161 (char 160)

In [6]:
df.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

In [7]:
df.shape

(23450, 6)

In [8]:
df.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='object')

In [9]:
df=df[['short_description']]

In [10]:
df

                                       short_description
0      Health experts said it is too early to predict...
1      He was subdued by passengers and crew when he ...
2      "Until you have a dog you don't understand wha...
3      "Accidentally put grown-up toothpaste on my to...
4      Amy Cooper accused investment firm Franklin Te...
...                                                  ...
23445  This includes a former managing editor at Broa...
23446  He is scheduled to appear at the Family Resear...
23447  The actress has gone on the defense after repo...
23448                      A little DNA goes a long way.
23449  The comedian was best known for his appearance...

[23450 rows x 1 columns]

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df.shape

(23359, 1)

In [13]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [14]:
tokenizer = Tokenizer(oov_token='<OOV>')

In [15]:
tokenizer.fit_on_texts(df['short_description'])

In [16]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'for': 8,
 'is': 9,
 'on': 10,
 'that': 11,
 'said': 12,
 'was': 13,
 'with': 14,
 'his': 15,
 'it': 16,
 'are': 17,
 'at': 18,
 'he': 19,
 'have': 20,
 'as': 21,
 'has': 22,
 'an': 23,
 'this': 24,
 'be': 25,
 'from': 26,
 'trump': 27,
 'president': 28,
 '”': 29,
 'i': 30,
 'about': 31,
 'not': 32,
 'by': 33,
 'you': 34,
 'but': 35,
 'new': 36,
 'her': 37,
 'who': 38,
 'after': 39,
 'will': 40,
 'one': 41,
 'people': 42,
 'their': 43,
 'more': 44,
 'been': 45,
 'out': 46,
 'they': 47,
 'we': 48,
 'year': 49,
 'up': 50,
 'she': 51,
 'former': 52,
 'all': 53,
 'were': 54,
 'u': 55,
 's': 56,
 'just': 57,
 'what': 58,
 'when': 59,
 'first': 60,
 'than': 61,
 'over': 62,
 'had': 63,
 'says': 64,
 'no': 65,
 'or': 66,
 'like': 67,
 'house': 68,
 'would': 69,
 'two': 70,
 'some': 71,
 'if': 72,
 "it's": 73,
 'time': 74,
 'your': 75,
 'into': 76,
 'can': 77,
 'state': 78,
 'my': 79,
 'so': 80,
 'also': 81,
 'show': 82,
 'say': 83,
 'how': 84,
 'last': 85,
 'now': 86,
 'could': 87,
 'its': 88,
 'white': 89,
 'our': 90,
 'against': 91,
 'host': 92,
 'do': 93,
 'during': 94,
 'women': 95,
 'him': 96,
 'years': 97,
 'old': 98,
 'star': 99,
 'day': 100,
 'news': 101,
 'get': 102,
 'donald': 103,
 'told': 104,
 'week': 105,
 'there': 106,
 "trump's": 107,
 'back': 108,
 'other': 109,
 'them': 110,
 'most': 111,
 'before': 112,
 'being': 113,
 'police': 114,
 'which': 115,
 'made': 116,
 'make': 117,
 'even': 118,
 'me': 119,
 'sexual': 120,
 'country': 121,
 'may': 122,
 'actor': 123,
 '—': 124,
 'know': 125,
 'black': 126,
 'called': 127,
 'these': 128,
 'world': 129,
 'republican': 130,
 'many': 131,
 'only': 132,
 'it’s': 133,
 'while': 134,
 'man': 135,
 'late': 136,
 'american': 137,
 'off': 138,
 'since': 139,
 'right': 140,
 'down': 141,
 'accused': 142,
 'want': 143,
 'campaign': 144,
 'because': 145,
 'should': 146,
 'still': 147,
 'us': 148,
 'school': 149,
 'take': 150,
 'health': 151,
 'election': 152,
 'way': 153,
 'government': 154,
 'going': 155,
 '000': 156,
 'officials': 157,
 'did': 158,
 'too': 159,
 'three': 160,
 'democratic': 161,
 'national': 162,
 'media': 163,
 'much': 164,
 'life': 165,
 'long': 166,
 '19': 167,
 'york': 168,
 'gop': 169,
 'public': 170,
 'bill': 171,
 'wrote': 172,
 'senate': 173,
 'law': 174,
 'coronavirus': 175,
 'court': 176,
 'states': 177,
 'think': 178,
 'got': 179,
 'home': 180,
 'own': 181,
 '“i': 182,
 'never': 183,
 'federal': 184,
 'covid': 185,
 'really': 186,
 'twitter': 187,
 'good': 188,
 'family': 189,
 'where': 190,
 'need': 191,
 'killed': 192,
 'very': 193,
 'senator': 194,
 "don't": 195,
 "president's": 196,
 'help': 197,
 'why': 198,
 'any': 199,
 'reportedly': 200,
 'work': 201,
 'fox': 202,
 'go': 203,
 'woman': 204,
 'days': 205,
 'least': 206,
 'million': 207,
 'administration': 208,
 'city': 209,
 'attorney': 210,
 'those': 211,
 'attack': 212,
 'republicans': 213,
 'don’t': 214,
 'actress': 215,
 'found': 216,
 'rights': 217,
 'video': 218,
 'death': 219,
 'face': 220,
 'history': 221,
 'singer': 222,
 'gun': 223,
 'democrats': 224,
 "he's": 225,
 'month': 226,
 'took': 227,
 'children': 228,
 'secretary': 229,
 'social': 230,
 'political': 231,
 'times': 232,
 'night': 233,
 'men': 234,
 'sunday': 235,
 'best': 236,
 'biden': 237,
 'change': 238,
 'see': 239,
 'director': 240,
 'end': 241,
 'rep': 242,
 'pandemic': 243,
 'around': 244,
 'look': 245,
 'come': 246,
 'under': 247,
 '1': 248,
 'here': 249,
 'love': 250,
 'according': 251,
 'without': 252,
 'next': 253,
 '“the': 254,
 'group': 255,
 'support': 256,
 'through': 257,
 'big': 258,
 'war': 259,
 'justice': 260,
 'anti': 261,
 'office': 262,
 'comes': 263,
 'every': 264,
 'another': 265,
 'part': 266,
 'care': 267,
 'decision': 268,
 'party': 269,
 'tax': 270,
 'again': 271,
 'company': 272,
 'power': 273,
 'between': 274,
 'americans': 275,
 'young': 276,
 'same': 277,
 'investigation': 278,
 'congress': 279,
 'high': 280,
 'well': 281,
 'used': 282,
 'film': 283,
 'post': 284,
 'little': 285,
 'put': 286,
 'set': 287,
 'security': 288,
 'deal': 289,
 'north': 290,
 'things': 291,
 'including': 292,
 'vote': 293,
 'lot': 294,
 'series': 295,
 'died': 296,
 'second': 297,
 'department': 298,
 'allegations': 299,
 'asked': 300,
 'move': 301,
 'california': 302,
 'sen': 303,
 'story': 304,
 'ever': 305,
 'leader': 306,
 'report': 307,
 'hit': 308,
 'both': 309,
 'use': 310,
 'case': 311,
 'believe': 312,
 'official': 313,
 'four': 314,
 'came': 315,
 'latest': 316,
 'special': 317,
 'away': 318,
 'harassment': 319,
 'joe': 320,
 'general': 321,
 'monday': 322,
 'team': 323,
 'getting': 324,
 'washington': 325,
 'left': 326,
 'shot': 327,
 'shooting': 328,
 'already': 329,
 'michael': 330,
 '10': 331,
 'assault': 332,
 'russian': 333,
 'top': 334,
 'person': 335,
 'money': 336,
 'america': 337,
 'wants': 338,
 'far': 339,
 'united': 340,
 'shows': 341,
 'co': 342,
 "didn't": 343,
 'months': 344,
 'something': 345,
 'thing': 346,
 'making': 347,
 "here's": 348,
 'trying': 349,
 'stop': 350,
 'violence': 351,
 'five': 352,
 'recent': 353,
 'lawmakers': 354,
 'russia': 355,
 'call': 356,
 'claims': 357,
 'past': 358,
 'trump’s': 359,
 'response': 360,
 'coming': 361,
 'does': 362,
 'climate': 363,
 'john': 364,
 'whether': 365,
 'went': 366,
 'chief': 367,
 'then': 368,
 'nearly': 369,
 'movie': 370,
 'fire': 371,
 'military': 372,
 "doesn't": 373,
 'florida': 374,
 'presidential': 375,
 'members': 376,
 'experts': 377,
 'texas': 378,
 'place': 379,
 'action': 380,
 'candidate': 381,
 'reported': 382,
 'ago': 383,
 'announced': 384,
 'run': 385,
 'i’m': 386,
 'across': 387,
 'child': 388,
 'working': 389,
 '2016': 390,
 'judge': 391,
 'tv': 392,
 'once': 393,
 'talk': 394,
 'tell': 395,
 'several': 396,
 'leaders': 397,
 'sex': 398,
 'give': 399,
 'among': 400,
 'control': 401,
 'policy': 402,
 'plan': 403,
 'real': 404,
 'daughter': 405,
 'kids': 406,
 'gov': 407,
 'press': 408,
 'others': 409,
 'weeks': 410,
 'keep': 411,
 'thousands': 412,
 'open': 413,
 'students': 414,
 'food': 415,
 'comedian': 416,
 'few': 417,
 'might': 418,
 'season': 419,
 'tweeted': 420,
 'known': 421,
 'tuesday': 422,
 'enough': 423,
 'live': 424,
 'taking': 425,
 'friday': 426,
 'legal': 427,
 'democrat': 428,
 'parents': 429,
 'calling': 430,
 "there's": 431,
 'south': 432,
 'authorities': 433,
 'saturday': 434,
 "they're": 435,
 'major': 436,
 'head': 437,
 'amid': 438,
 'son': 439,
 'governor': 440,
 'saying': 441,
 'dead': 442,
 'led': 443,
 'd': 444,
 'must': 445,
 'bad': 446,
 "can't": 447,
 'fbi': 448,
 'event': 449,
 'community': 450,
 "won't": 451,
 'abuse': 452,
 'today': 453,
 'percent': 454,
 'feel': 455,
 '2020': 456,
 '2017': 457,
 'become': 458,
 'claimed': 459,
 'name': 460,
 'yet': 461,
 'charges': 462,
 '2': 463,
 'allegedly': 464,
 'expected': 465,
 'cnn': 466,
 'voters': 467,
 'won': 468,
 'comments': 469,
 'words': 470,
 'supreme': 471,
 'race': 472,
 'wanted': 473,
 'better': 474,
 'number': 475,
 '6': 476,
 'information': 477,
 "she's": 478,
 '3': 479,
 "that's": 480,
 'great': 481,
 'actually': 482,
 'crisis': 483,
 'everyone': 484,
 'behind': 485,
 'interview': 486,
 'following': 487,
 'vice': 488,
 'fight': 489,
 'role': 490,
 'find': 491,
 'likely': 492,
 'game': 493,
 'misconduct': 494,
 'lgbtq': 495,
 'having': 496,
 'moment': 497,
 'music': 498,
 'win': 499,
 'workers': 500,
 'job': 501,
 'later': 502,
 'wife': 503,
 'lives': 504,
 'didn’t': 505,
 'thought': 506,
 'committee': 507,
 'am': 508,
 'until': 509,
 'conservative': 510,
 'hollywood': 511,
 'pay': 512,
 'received': 513,
 'free': 514,
 "you're": 515,
 'earlier': 516,
 'meeting': 517,
 'looking': 518,
 'let': 519,
 'service': 520,
 '5': 521,
 'using': 522,
 'instagram': 523,
 'hundreds': 524,
 '20': 525,
 '“we': 526,
 'defense': 527,
 'groups': 528,
 'gave': 529,
 'fans': 530,
 'always': 531,
 'less': 532,
 'though': 533,
 'six': 534,
 'mass': 535,
 'question': 536,
 'future': 537,
 'taken': 538,
 'king': 539,
 'clear': 540,
 'seen': 541,
 'rapper': 542,
 'step': 543,
 'wednesday': 544,
 'nothing': 545,
 'anyone': 546,
 'capitol': 547,
 'plans': 548,
 'decades': 549,
 'prime': 550,
 'movement': 551,
 'border': 552,
 'someone': 553,
 'record': 554,
 'air': 555,
 'robert': 556,
 'running': 557,
 'hours': 558,
 'released': 559,
 'almost': 560,
 '2018': 561,
 'victims': 562,
 'doing': 563,
 'such': 564,
 'laws': 565,
 'previously': 566,
 'hard': 567,
 'order': 568,
 'himself': 569,
 'facebook': 570,
 'questions': 571,
 'huffpost': 572,
 'cases': 573,
 'james': 574,
 'agency': 575,
 'calls': 576,
 'appeared': 577,
 'local': 578,
 'fired': 579,
 'early': 580,
 'full': 581,
 'lost': 582,
 'act': 583,
 'obama': 584,
 'water': 585,
 'different': 586,
 'book': 587,
 'lawyer': 588,
 "isn't": 589,
 'david': 590,
 'letter': 591,
 'legislation': 592,
 'issues': 593,
 'red': 594,
 'together': 595,
 'attacks': 596,
 'international': 597,
 'prison': 598,
 'minister': 599,
 'nominee': 600,
 'killing': 601,
 'despite': 602,
 'staff': 603,
 'mayor': 604,
 'female': 605,
 'abortion': 606,
 'bring': 607,
 'force': 608,
 'read': 609,
 'alleged': 610,
 'human': 611,
 'reports': 612,
 'district': 613,
 'ukraine': 614,
 'each': 615,
 'business': 616,
 'daily': 617,
 'friends': 618,
 'civil': 619,
 'you’re': 620,
 'that’s': 621,
 'doesn’t': 622,
 'program': 623,
 'finally': 624,
 'problem': 625,
 'message': 626,
 'photo': 627,
 "i'm": 628,
 'immigration': 629,
 'politics': 630,
 'held': 631,
 'r': 632,
 'looks': 633,
 'stand': 634,
 'share': 635,
 'march': 636,
 'important': 637,
 'felt': 638,
 'speech': 639,
 'system': 640,
 '15': 641,
 'alabama': 642,
 'nation': 643,
 'protesters': 644,
 "we're": 645,
 '12': 646,
 'families': 647,
 'warned': 648,
 'union': 649,
 'happy': 650,
 'possible': 651,
 'instead': 652,
 'university': 653,
 '“this': 654,
 'needs': 655,
 'wrong': 656,
 'christmas': 657,
 'shared': 658,
 'nuclear': 659,
 'counsel': 660,
 'activist': 661,
 '18': 662,
 'watch': 663,
 'lawsuit': 664,
 '30': 665,
 'matter': 666,
 'hold': 667,
 'sure': 668,
 'wall': 669,
 'claim': 670,
 'anything': 671,
 'center': 672,
 'thursday': 673,
 'everything': 674,
 'turned': 675,
 'pop': 676,
 'makes': 677,
 'ex': 678,
 'protect': 679,
 'serious': 680,
 'officer': 681,
 'ahead': 682,
 'near': 683,
 'father': 684,
 'list': 685,
 'process': 686,
 'half': 687,
 'hope': 688,
 'teachers': 689,
 'leave': 690,
 'toward': 691,
 'issue': 692,
 'kim': 693,
 'tweet': 694,
 'effort': 695,
 'gets': 696,
 'efforts': 697,
 'based': 698,
 'data': 699,
 'charged': 700,
 'break': 701,
 'girl': 702,
 'executive': 703,
 '―': 704,
 '17': 705,
 'evidence': 706,
 'incident': 707,
 'virginia': 708,
 'mark': 709,
 'lady': 710,
 'point': 711,
 'network': 712,
 'schools': 713,
 'culture': 714,
 'trial': 715,
 'truth': 716,
 'ban': 717,
 'congressional': 718,
 'recently': 719,
 'lead': 720,
 'global': 721,
 'we’re': 722,
 'arrested': 723,
 'mental': 724,
 'safety': 725,
 'try': 726,
 'soon': 727,
 'stars': 728,
 'spoke': 729,
 'gay': 730,
 'can’t': 731,
 'kind': 732,
 'often': 733,
 'progressive': 734,
 'mother': 735,
 'conspiracy': 736,
 'jan': 737,
 'multiple': 738,
 'member': 739,
 'powerful': 740,
 'voting': 741,
 'continue': 742,
 'line': 743,
 'virus': 744,
 'husband': 745,
 'probably': 746,
 'related': 747,
 '4': 748,
 '100': 749,
 'he’s': 750,
 'done': 751,
 'mike': 752,
 'intelligence': 753,
 'helped': 754,
 'organization': 755,
 'inside': 756,
 'play': 757,
 'county': 758,
 'showed': 759,
 'posted': 760,
 'became': 761,
 'activists': 762,
 'tweets': 763,
 'statement': 764,
 'talking': 765,
 'foreign': 766,
 'third': 767,
 'body': 768,
 'girls': 769,
 'countries': 770,
 'due': 771,
 'term': 772,
 'access': 773,
 'criminal': 774,
 'apparently': 775,
 'advocates': 776,
 'board': 777,
 'immigrants': 778,
 'true': 779,
 'holiday': 780,
 'heart': 781,
 'reality': 782,
 'online': 783,
 'ways': 784,
 'age': 785,
 'biggest': 786,
 'forces': 787,
 'threat': 788,
 'small': 789,
 'adviser': 790,
 'officers': 791,
 '50': 792,
 'faces': 793,
 'suspect': 794,
 'self': 795,
 'spread': 796,
 'tonight': 797,
 'means': 798,
 'netflix': 799,
 'voted': 800,
 'start': 801,
 'sent': 802,
 'racist': 803,
 'ceremony': 804,
 'british': 805,
 'began': 806,
 'west': 807,
 'companies': 808,
 'tried': 809,
 'mexico': 810,
 'light': 811,
 'male': 812,
 'democracy': 813,
 'probe': 814,
 'personal': 815,
 'victory': 816,
 'speak': 817,
 'korea': 818,
 'reason': 819,
 'moore': 820,
 'protests': 821,
 'scott': 822,
 'started': 823,
 'heard': 824,
 'outside': 825,
 'paid': 826,
 'jones': 827,
 'brought': 828,
 'gender': 829,
 'forward': 830,
 'fighting': 831,
 'critics': 832,
 'address': 833,
 'cut': 834,
 "wasn't": 835,
 'winning': 836,
 'artist': 837,
 'award': 838,
 'weekend': 839,
 'spent': 840,
 'current': 841,
 'comedy': 842,
 'jr': 843,
 'dr': 844,
 'continues': 845,
 'k': 846,
 'denied': 847,
 'couple': 848,
 '“it': 849,
 'education': 850,
 'whole': 851,
 'olympic': 852,
 'fall': 853,
 'hurricane': 854,
 'key': 855,
 'described': 856,
 'elections': 857,
 'speaker': 858,
 'murder': 859,
 'author': 860,
 'hearing': 861,
 'weinstein': 862,
 'goes': 863,
 'pro': 864,
 'longer': 865,
 'viral': 866,
 'growing': 867,
 'popular': 868,
 'failed': 869,
 'career': 870,
 'confirmed': 871,
 'supporters': 872,
 'residents': 873,
 'revealed': 874,
 'november': 875,
 'billion': 876,
 'fake': 877,
 'involved': 878,
 'ryan': 879,
 'san': 880,
 'industry': 881,
 'criticism': 882,
 'student': 883,
 'games': 884,
 'seven': 885,
 'met': 886,
 'economic': 887,
 'winter': 888,
 'brown': 889,
 '“it’s': 890,
 'idea': 891,
 'seems': 892,
 'pretty': 893,
 'impeachment': 894,
 'los': 895,
 'park': 896,
 'saw': 897,
 'morning': 898,
 'potential': 899,
 'ceo': 900,
 'dozens': 901,
 'release': 902,
 'short': 903,
 'giving': 904,
 'voter': 905,
 'street': 906,
 'meet': 907,
 'queer': 908,
 'f': 909,
 'experience': 910,
 'controversial': 911,
 'clinton': 912,
 'yes': 913,
 'hate': 914,
 'stories': 915,
 'missing': 916,
 'trip': 917,
 '7': 918,
 'single': 919,
 'church': 920,
 'nations': 921,
 'beyond': 922,
 'mind': 923,
 'color': 924,
 'talks': 925,
 'living': 926,
 'employees': 927,
 'jimmy': 928,
 'friend': 929,
 'there’s': 930,
 "'": 931,
 'emergency': 932,
 'given': 933,
 'protest': 934,
 'sexually': 935,
 '25': 936,
 'knew': 937,
 'drug': 938,
 'hopes': 939,
 'class': 940,
 'able': 941,
 'c': 942,
 'george': 943,
 'mueller': 944,
 'anchor': 945,
 'visit': 946,
 'victim': 947,
 "state's": 948,
 'attention': 949,
 '11': 950,
 'players': 951,
 'muslim': 952,
 'giant': 953,
 'deaths': 954,
 'rules': 955,
 'baby': 956,
 'risk': 957,
 'mean': 958,
 'favorite': 959,
 'millions': 960,
 'congressman': 961,
 'andrew': 962,
 'asian': 963,
 'hair': 964,
 'cause': 965,
 'pass': 966,
 'hear': 967,
 'themselves': 968,
 'behavior': 969,
 'saudi': 970,
 'close': 971,
 'worked': 972,
 'super': 973,
 'performance': 974,
 'along': 975,
 "country's": 976,
 'strong': 977,
 'com': 978,
 'duchess': 979,
 'currently': 980,
 'rule': 981,
 'facing': 982,
 'song': 983,
 'forced': 984,
 'crime': 985,
 'accusations': 986,
 'angeles': 987,
 'stage': 988,
 'awards': 989,
 'choice': 990,
 '8': 991,
 'guilty': 992,
 'cast': 993,
 'worst': 994,
 'chris': 995,
 'passed': 996,
 'racism': 997,
 'island': 998,
 'playing': 999,
 'emotional': 1000,
 ...}

In [17]:
len(tokenizer.word_index)

28447

In [18]:
df=tokenizer.texts_to_sequences(df['short_description'])

In [19]:
df

[[151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36,
  14612,
  2,
  55,
  56,
  1482,
  8,
  2,
  853],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3,
  2,
  55,
  56,
  8429,
  262,
  7,
  895,
  987],
 [509, 34, 20, 4, 1406, 34, 195, 1367, 58, 87, 25, 8430],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201,
  14,
  4,
  1117,
  14616,
  10576,
  7,
  14617,
  7100],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39,
  218,
  5,
  2,
  1253,
  896,
  2055,
  366,
  866],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322,
  39,
  37,
  189,
  382,
  37,
  916,
  433,
  12],
 [1285,
  11,
  485,
  34,
  23,
  945,
  8,
  36,
  7101,
  14619,
  300,
  1218,
  1976,
  3896,
  21,
  51,
  3202,
  50,
  23,
  486],
 [44,
  61,
  687,
  4,
  207,
  42,
  2715,
  252,
  585,
  520,
  160,
  205,
  39,
  2,
  1006,
  4943,
  2,
  55,
  56,
  2716],
 [7,
  14620,
  240,
  14621,
  5527,
  4524,
  498,
  10578,
  14,
  2,
  1368,
  5,
  8432,
  6,
  5528,
  3,
  395,
  4,
  44,
  6191,
  629,
  304],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581,
  14623,
  5529,
  5,
  355,
  6,
  88,
  2850,
  259],
 [8433,
  22,
  246,
  247,
  1097,
  26,
  396,
  1671,
  1977,
  14624,
  38,
  143,
  3,
  256,
  4,
  611,
  217,
  144,
  91,
  1286,
  18,
  2,
  129,
  3203],
 [2,
  707,
  4944,
  4,
  867,
  1407,
  5,
  821,
  91,
  2,
  3022,
  8,
  8434,
  8435,
  38,
  13,
  41,
  5,
  2,
  111,
  3646,
  397,
  7,
  14625,
  2341,
  630],
 [854,
  14626,
  4943,
  2,
  7102,
  6,
  10579,
  3897,
  6,
  13,
  6192,
  3,
  10580,
  358,
  14627,
  502,
  24,
  105],
 [41,
  3204,
  357,
  11,
  19,
  10581,
  42,
  10,
  2,
  1437,
  1074,
  396,
  868,
  14628,
  3,
  1720,
  4,
  14629,
  4191],
 [510,
  661,
  708,
  1171,
  2,
  503,
  5,
  471,
  176,
  260,
  5530,
  1171,
  22,
  1784,
  3,
  4945,
  7,
  4,
  8436,
  486,
  14,
  2,
  68,
  1903,
  1022,
  2,
  737,
  476,
  1785],
 [14630,
  554,
  1219,
  917,
  3,
  8437,
  1172,
  897,
  96,
  4946,
  1721,
  918,
  14631,
  232,
  6,
  1023,
  369,
  14632,
  207,
  1408],
 [1978,
  14633,
  330,
  855,
  8438,
  8439,
  6,
  6193,
  10582,
  2,
  4947,
  82,
  1144,
  2,
  3205,
  5,
  4,
  6194,
  580,
  8440,
  3898],
 [14634,
  14635,
  38,
  754,
  2,
  895,
  987,
  4948,
  499,
  160,
  129,
  295,
  5531,
  14,
  15,
  3421,
  6195,
  10583,
  22,
  296],
 [2,
  14636,
  6,
  14637,
  2576,
  1369,
  697,
  3,
  10584,
  50,
  314,
  8441,
  87,
  287,
  2,
  988,
  8,
  2056,
  3,
  8442,
  2,
  259],
 [2,
  7102,
  6,
  10579,
  3897,
  154,
  2342,
  4,
  10585,
  21,
  2,
  7103,
  1006,
  1483,
  3206,
  10586,
  2234,
  62,
  2,
  6196,
  3207,
  6,
  2235,
  2851],
 [8,
  2,
  358,
  662,
  344,
  511,
  22,
  3899,
  14638,
  2,
  2577,
  39,
  612,
  11,
  2,
  14639,
  6197,
  376,
  5,
  1438,
  137,
  1484,
  1672,
  65,
  126,
  376],
 [28, 593, 8443, 21, 2236, 14, 1024, 1173],
 [2,
  1006,
  3023,
  46,
  2,
  273,
  4949,
  6,
  8444,
  4192,
  6,
  8445,
  7,
  2235,
  2851,
  190,
  2,
  440,
  12,
  2,
  1605,
  13,
  14640,
  29],
 [2,
  919,
  6198,
  1530,
  13,
  6199,
  7,
  2,
  162,
  6200,
  555,
  3208,
  10,
  235,
  59,
  16,
  2578,
  76,
  4,
  1409,
  601,
  2,
  2237,
  157,
  12],
 [23, 1254, 3209, 227, 10, 4, 586, 455, 21, 1531, 2146, 6201, 76, 100, 14641],
 [709, 14642, 4, 2579, 1075, 6, 3900, 6202, 13, 6203, 7, 2852, 7, 1606, 456],
 [1786, 1722, 183, 63, 4, 2853, 1118, 2147, 124, 509, 235],
 [28,
  320,
  237,
  6,
  60,
  710,
  4193,
  237,
  54,
  400,
  412,
  5,
  10587,
  124,
  26,
  10588,
  6,
  4525,
  3,
  10589,
  6,
  129,
  397,
  124,
  3,
  512,
  43,
  7104],
 [2,
  10590,
  240,
  12,
  6204,
  5,
  15,
  6205,
  370,
  17,
  147,
  6206,
  14,
  674,
  621,
  46,
  106,
  128,
  205],
 [14643,
  556,
  421,
  21,
  2,
  1220,
  4526,
  135,
  22,
  7105,
  2,
  14644,
  14645,
  6,
  2,
  4194,
  78,
  1007],
 [55,
  56,
  28,
  320,
  237,
  7,
  1607,
  8,
  2,
  3022,
  5,
  1119,
  1255,
  2448,
  64,
  15,
  781,
  366,
  46,
  3,
  2,
  1572,
  189,
  3024,
  2,
  14646,
  219,
  326,
  4,
  10591,
  4950,
  29],
 [602,
  2717,
  1198,
  477,
  43,
  201,
  835,
  14647,
  1840,
  6,
  7,
  71,
  573,
  2,
  2449,
  14648,
  513,
  4951,
  2,
  262,
  5,
  4952,
  321,
  382],
 [10, 322, 2, 4195, 60, 170, 7106, 5, 3025, 1723, 3210, 10592, 6, 4953, 7107],
 [2, 167, 49, 98, 200, 1975, 76, 2, 14649, 7, 4, 869, 2148, 3, 2580, 114],
 [3422,
  331,
  97,
  42,
  40,
  25,
  5532,
  3,
  2,
  1979,
  2238,
  1006,
  21,
  4,
  10593,
  1006,
  29],
 [2235,
  2851,
  13,
  247,
  4,
  854,
  663,
  434,
  21,
  2,
  1006,
  10594,
  2854,
  2,
  55,
  56,
  2716],
 [2,
  129,
  151,
  755,
  9,
  2057,
  2,
  4196,
  31,
  4,
  14650,
  14651,
  7,
  2,
  1045,
  5,
  2,
  1199,
  4192,
  7,
  3901,
  24,
  1327,
  21,
  2058,
  6,
  1046,
  500,
  10,
  2,
  1145,
  472,
  3,
  1146,
  4197,
  5,
  14652,
  6,
  109,
  4527],
 [3026,
  20,
  1370,
  3647,
  11,
  1673,
  170,
  208,
  5,
  585,
  4528,
  622,
  201,
  124,
  35,
  621,
  86,
  10,
  2,
  2239,
  7,
  2240],
 [8446,
  7,
  2,
  221,
  5,
  2,
  14653,
  3902,
  262,
  22,
  4,
  3423,
  5,
  8447,
  443,
  148,
  3,
  14654,
  3648,
  29,
  2149,
  330,
  1485,
  104,
  2,
  163],
 [2,
  240,
  5,
  2,
  1532,
  8448,
  283,
  1608,
  4,
  1147,
  5,
  2,
  457,
  3649,
  8,
  2,
  4529,
  4198,
  7,
  2,
  4530,
  4199,
  3424],
 [130,
  2241,
  62,
  2,
  8449,
  55,
  56,
  4531,
  26,
  2852,
  3027,
  5533,
  256,
  8,
  14655,
  1609],
 [1904,
  3028,
  4954,
  582,
  23,
  1610,
  6,
  22,
  4532,
  5,
  4200,
  756,
  37,
  768,
  26,
  4,
  7108,
  7109,
  7110,
  4201,
  11,
  192,
  37,
  1980,
  6,
  160,
  109,
  126,
  769,
  756,
  23,
  642,
  920,
  4955,
  97,
  383],
 [4,
  10595,
  585,
  7111,
  22,
  45,
  4202,
  8,
  7112,
  1120,
  6,
  2,
  78,
  40,
  350,
  6207,
  46,
  514,
  8450,
  585,
  10,
  434],
 [254,
  10596,
  5,
  2,
  14656,
  124,
  14657,
  2718,
  557,
  82,
  124,
  9,
  1674,
  3,
  971,
  7,
  2059,
  10597,
  4,
  947,
  5,
  284,
  243,
  10598,
  7,
  3903,
  5534,
  7,
  36,
  168],
 [2,
  52,
  89,
  68,
  367,
  5,
  603,
  22,
  675,
  62,
  1439,
  21,
  266,
  5,
  4,
  184,
  278,
  76,
  2,
  737,
  476,
  1981,
  332,
  10,
  2,
  547],
 [2,
  10599,
  137,
  6208,
  36,
  587,
  14658,
  13,
  2060,
  4956,
  232,
  124,
  509,
  51,
  366,
  2242,
  3,
  37,
  2855,
  8,
  256],
 [14659,
  3904,
  5535,
  3,
  2,
  3211,
  1371,
  6,
  631,
  141,
  37,
  14660,
  509,
  114,
  2061,
  7113,
  24,
  835,
  2,
  60,
  74,
  3904,
  122,
  20,
  3029,
  4,
  165],
 [2,
  1025,
  1076,
  12,
  51,
  972,
  46,
  8,
  352,
  558,
  4,
  100,
  8,
  37,
  490,
  7,
  2,
  36,
  380,
  370],
 [2,
  782,
  99,
  104,
  574,
  2719,
  478,
  14661,
  46,
  145,
  1982,
  73,
  32,
  389,
  2720,
  386,
  563],
 [2,
  1786,
  1722,
  10600,
  17,
  1724,
  3,
  491,
  46,
  38,
  327,
  2,
  4957,
  1256,
  2062,
  97,
  383],
 [2,
  2343,
  836,
  542,
  2344,
  99,
  1257,
  228,
  18,
  2,
  3030,
  14662,
  149,
  7,
  4533,
  4534,
  3,
  117,
  2,
  1200],
 [6209,
  2,
  52,
  55,
  56,
  1725,
  3,
  2,
  340,
  921,
  6,
  4,
  10601,
  14663,
  7,
  4958,
  2243,
  631,
  5536,
  14,
  333,
  397],
 [2, 2581, 989, 804, 582, 2856, 248, 521, 207, 1486, 1905, 3, 88, 1981, 623],
 [89,
  68,
  408,
  229,
  10602,
  3425,
  7114,
  12,
  4,
  7115,
  1328,
  9,
  32,
  7116,
  6,
  69,
  2063,
  647,
  21,
  281,
  21,
  1533],
 [2,
  948,
  321,
  8451,
  9,
  3212,
  3,
  220,
  52,
  14664,
  604,
  14665,
  14666,
  632,
  7,
  2,
  321,
  152],
 [4,
  55,
  56,
  1528,
  11,
  14667,
  1198,
  783,
  357,
  612,
  11,
  8452,
  8,
  477,
  31,
  1906,
  101,
  3905,
  10,
  3650,
  17,
  492,
  3,
  1077,
  50,
  1121,
  10603,
  14,
  2582],
 [10, 4, 4535, 2450, 2150, 1487, 4203, 248, 39, 4, 6210, 2583, 7, 1573],
 [2, 240, 13, 236, 421, 8, 2, 4959, 370, 14668],
 [435,
  5537,
  8,
  7117,
  4536,
  47,
  83,
  40,
  197,
  3906,
  4960,
  267,
  33,
  14669,
  14670,
  10604,
  11,
  20,
  10605,
  7,
  2,
  243],
 [1174,
  362,
  32,
  6211,
  594,
  6,
  1440,
  2,
  28,
  12,
  322,
  4537,
  1174,
  9,
  345,
  48,
  77,
  93,
  595],
 [38, 48, 20, 10, 2, 1409, 9, 38, 722, 1611, 757, 29, 822, 104, 202, 101, 235],
 [2,
  10606,
  2451,
  83,
  8453,
  1726,
  451,
  20,
  3,
  3651,
  14,
  2,
  3031,
  66,
  1078,
  10607,
  6,
  2584,
  10608,
  232,
  3,
  3213,
  43,
  1612],
 [14671, 10609, 2151, 14, 2, 2857, 14672, 6, 823, 15, 174, 1201, 870, 7, 390],
 [224,
  7,
  2,
  2585,
  44,
  3907,
  68,
  613,
  17,
  8454,
  38,
  40,
  150,
  10,
  4,
  868,
  130,
  52,
  604],
 [237,
  548,
  3,
  3652,
  949,
  3,
  4,
  36,
  14673,
  1369,
  1221,
  11,
  3908,
  3,
  8455,
  522,
  1787,
  2586,
  3,
  1613,
  91,
  738,
  7118],
 [2,
  1175,
  698,
  837,
  22,
  216,
  6212,
  784,
  3,
  3426,
  2858,
  31,
  605,
  4961,
  7119,
  6,
  1727,
  7,
  37,
  5538],
 [133,
  32,
  31,
  14674,
  66,
  118,
  14675,
  2,
  6213,
  5,
  10610,
  14676,
  1258,
  2,
  36,
  1441,
  3427,
  15,
  3214,
  124,
  264,
  14677,
  5,
  16],
 [4538,
  14678,
  2721,
  10611,
  14679,
  7,
  2,
  55,
  56,
  413,
  1008,
  3,
  6214,
  15,
  60,
  1079,
  2722,
  18,
  785,
  167,
  6,
  458,
  2,
  4204,
  135,
  3,
  301,
  50,
  3,
  65,
  248,
  7,
  2,
  6215],
 [3653,
  116,
  1788,
  91,
  4,
  1442,
  1728,
  302,
  4962,
  11,
  13,
  147,
  867,
  6,
  1729,
  412,
  5,
  4539,
  1675],
 [28,
  320,
  237,
  22,
  2723,
  2,
  4205,
  1443,
  5,
  2,
  4206,
  950,
  596,
  425,
  266,
  7,
  4,
  10612,
  14680,
  7120,
  804,
  631,
  18,
  2,
  4207,
  247,
  4,
  7121,
  2234],
 [1979,
  10613,
  1259,
  4,
  711,
  8,
  8456,
  10,
  2,
  3654,
  596,
  14681,
  162,
  288,
  14682,
  5533,
  4,
  55,
  56,
  10614,
  10,
  14683,
  3428],
 [2,
  3032,
  41,
  5,
  2,
  331,
  786,
  6216,
  273,
  7122,
  7,
  2,
  129,
  22,
  45,
  7123,
  33,
  333,
  787,
  139,
  580,
  7,
  2,
  259,
  115,
  2723,
  88,
  8457,
  100,
  10,
  235],
 [14684,
  4208,
  9,
  1907,
  21,
  2,
  1122,
  3033,
  712,
  6,
  40,
  492,
  1841,
  1097,
  8,
  10615,
  6,
  137,
  3215,
  3,
  7124,
  2,
  3909,
  21,
  281],
 [2,
  260,
  298,
  1026,
  70,
  1908,
  2587,
  8,
  2,
  490,
  359,
  323,
  1026,
  4,
  1908,
  391,
  6,
  4,
  588],
 [2,
  240,
  104,
  2,
  2064,
  19,
  13,
  973,
  3034,
  3,
  25,
  624,
  14685,
  50,
  370,
  70,
  124,
  21,
  19,
  22,
  160,
  2724,
  14686,
  7,
  2,
  1983],
 [2452,
  527,
  2725,
  384,
  11,
  1372,
  40,
  25,
  1789,
  108,
  7,
  70,
  1176,
  190,
  4,
  1574,
  4209,
  1842,
  22,
  116,
  1907,
  3035],
 [39,
  4,
  331,
  100,
  1843,
  1407,
  11,
  369,
  6217,
  2,
  6218,
  4949,
  1177,
  302,
  179,
  7125,
  1222,
  35,
  81,
  4,
  10616,
  3429,
  1006],
 [1574, 787, 17, 2152, 36, 2065, 7, 43, 14687, 91, 333, 787, 7, 2, 2859],
 [8458,
  1534,
  119,
  7,
  4,
  2066,
  5,
  5539,
  8,
  1984,
  97,
  5,
  520,
  29,
  2,
  676,
  99,
  104,
  2,
  1260,
  39,
  19,
  8459,
  15,
  8460,
  3430,
  3431,
  974],
 [14688,
  14689,
  1790,
  87,
  25,
  4,
  436,
  2244,
  3,
  2,
  632,
  1223,
  1614,
  688,
  5,
  7126],
 [309,
  805,
  6,
  597,
  4540,
  1287,
  2,
  2860,
  5,
  2,
  55,
  14690,
  56,
  2718,
  10617,
  6219],
 [2,
  167,
  49,
  98,
  222,
  5540,
  6,
  2453,
  1256,
  40,
  1676,
  2,
  2238,
  14691,
  838,
  8,
  37,
  1373,
  10,
  261,
  3910,
  697],
 [1123,
  26,
  10618,
  4541,
  5541,
  12,
  770,
  6220,
  44,
  1224,
  8,
  363,
  238,
  146,
  20,
  1009,
  24,
  1288],
 [2067,
  758,
  170,
  2153,
  556,
  14692,
  13,
  723,
  7,
  2,
  2861,
  4210,
  5,
  1410,
  2068,
  38,
  63,
  45,
  1022,
  15,
  262],
 [2, 1027, 7127, 7, 2588, 62, 2, 52, 60, 5542, 14693, 990, 8, 2, 14694, 100],
 [2,
  123,
  12,
  19,
  13,
  80,
  4542,
  14695,
  134,
  328,
  2,
  295,
  4963,
  11,
  19,
  4543,
  8,
  15,
  165,
  6,
  13,
  1411,
  1730,
  2,
  3911,
  134,
  3912],
 [2345,
  5,
  2,
  1731,
  459,
  10619,
  116,
  2,
  10608,
  14696,
  14697,
  35,
  2,
  948,
  1124,
  176,
  2060,
  11,
  3216],
 [2,
  664,
  64,
  1615,
  2454,
  3217,
  10620,
  3,
  1575,
  209,
  10621,
  677,
  16,
  1412,
  8,
  42,
  522,
  14698,
  10622,
  66,
  14699,
  3,
  310,
  110],
 [2,
  371,
  7,
  14700,
  23,
  209,
  806,
  136,
  422,
  6,
  2862,
  309,
  500,
  6,
  2863,
  756,
  2,
  6221,
  304,
  6222],
 [2,
  5543,
  951,
  1985,
  40,
  624,
  25,
  4,
  739,
  5,
  2,
  10623,
  10624,
  14701,
  14,
  4544,
  109,
  3655,
  387,
  5544],
 [7,
  111,
  5,
  2,
  1329,
  6223,
  341,
  11,
  2864,
  10625,
  952,
  3656,
  54,
  4211,
  1225,
  14702,
  66,
  14703,
  124,
  72,
  47,
  7128,
  18,
  53],
 [177,
  17,
  2346,
  108,
  6,
  279,
  9,
  3036,
  3,
  543,
  7,
  118,
  39,
  2,
  243,
  1986,
  2,
  3657,
  14704,
  14705],
 [1413,
  157,
  7,
  2865,
  378,
  83,
  23,
  580,
  898,
  273,
  8461,
  9,
  2589,
  1202,
  5545,
  118,
  21,
  3432,
  22,
  45,
  8462],
 [2,
  437,
  5,
  2,
  597,
  6216,
  1148,
  575,
  648,
  2,
  55,
  1096,
  288,
  1444,
  11,
  10626,
  193,
  193,
  6224,
  87,
  150,
  7129,
  18,
  14706],
 [564,
  596,
  20,
  458,
  4,
  867,
  788,
  3,
  55,
  56,
  713,
  14,
  396,
  280,
  2154,
  2726,
  382,
  139,
  85,
  49],
 [4, 297, 371, 192, 70, 42, 7, 1728, 302, 24, 839],
 [2,
  4545,
  14707,
  10627,
  8463,
  1677,
  179,
  7130,
  76,
  1844,
  5546,
  2155,
  7,
  4,
  331,
  4203,
  1445,
  3,
  2,
  5547],
 [2,
  209,
  1259,
  247,
  4,
  10595,
  585,
  2455,
  115,
  60,
  366,
  76,
  1678,
  10,
  1573,
  665],
 [2,
  230,
  163,
  953,
  13,
  6225,
  8,
  3037,
  5,
  699,
  3038,
  565,
  747,
  3,
  477,
  31,
  228,
  10,
  523],
 [106,
  9,
  36,
  280,
  10628,
  244,
  2,
  378,
  8464,
  170,
  713,
  11,
  147,
  589,
  3202,
  6,
  4,
  1535,
  114,
  3658,
  11,
  131,
  647,
  195,
  2347],
 [2,
  1732,
  263,
  39,
  2,
  237,
  208,
  871,
  11,
  2,
  333,
  372,
  7,
  1845,
  227,
  2456,
  5,
  1616,
  7131,
  8465,
  8,
  310,
  7,
  614],
 [2, 21, 16, 13, 222, 12, 19, 81, 622, 239, 131, 10629, 274, 498, 6, 1414],
 [10630,
  14708,
  12,
  2582,
  6226,
  2,
  899,
  8,
  2724,
  1536,
  319,
  6,
  118,
  351,
  10,
  152,
  100],
 [14709, 900, 3218, 1098, 63, 566, 5548, 576, 3, 1575, 2, 1099],
 [225,
  1791,
  7,
  79,
  10631,
  21,
  166,
  21,
  19,
  373,
  1446,
  119,
  66,
  79,
  189,
  2,
  7132,
  3913],
 [59,
  10632,
  14710,
  633,
  18,
  2,
  10633,
  11,
  3659,
  141,
  37,
  14711,
  51,
  447,
  197,
  1047,
  122,
  1488,
  59,
  4,
  1909,
  6227,
  37,
  1733,
  4546,
  1178,
  18,
  5549,
  3039,
  7,
  4547,
  378,
  601,
  167,
  228,
  6,
  70,
  689,
  6,
  1261,
  37,
  6,
  409,
  1489],
 [3040,
  14712,
  576,
  10,
  872,
  3,
  203,
  39,
  163,
  487,
  4548,
  2727,
  8466,
  304,
  1734,
  14713,
  1846,
  3,
  261,
  606,
  528],
 [114,
  7,
  2866,
  83,
  23,
  1735,
  22,
  45,
  116,
  7,
  2,
  8467,
  5,
  4,
  204,
  38,
  13,
  5550,
  134,
  10634],
 [873,
  5,
  7112,
  1048,
  126,
  1120,
  147,
  195,
  20,
  1792,
  585,
  39,
  3914,
  10605,
  2,
  2728,
  3041],
 [433,
  2457,
  11,
  44,
  2729,
  9,
  465,
  21,
  3219,
  14714,
  14715,
  26,
  1987,
  7133,
  3914,
  11,
  20,
  192,
  369,
  248,
  1910,
  42],
 [414,
  38,
  2245,
  2,
  122,
  1488,
  328,
  18,
  5549,
  3039,
  7,
  378,
  17,
  1203,
  2,
  1327,
  14,
  4,
  92,
  5,
  724,
  151,
  593,
  292,
  10635],
 [8468,
  6,
  1535,
  2234,
  14716,
  1490,
  5,
  14717,
  1049,
  10,
  235,
  5551,
  5552,
  2729,
  6,
  10636,
  280,
  4964,
  7,
  71,
  1847],
 [4965,
  418,
  1047,
  2,
  4212,
  5553,
  782,
  295,
  26,
  2,
  580,
  8440,
  2,
  4213,
  295,
  40,
  25,
  3660,
  18,
  2,
  4549,
  10637,
  14718,
  2458,
  7,
  1736],
 [4,
  2237,
  22,
  45,
  723,
  39,
  14719,
  4,
  789,
  7134,
  62,
  10638,
  2240,
  134,
  1729,
  3,
  1447,
  76,
  4,
  4214,
  1529],
 [266, 5, 2, 1172, 4215, 8469, 623, 2, 3433, 9, 2, 111, 740, 3, 1537],
 [4550, 1330, 2069, 14720, 4966, 33, 2590, 901, 12, 157],
 [14721,
  114,
  700,
  14722,
  14723,
  14724,
  14,
  160,
  14725,
  2070,
  5,
  3661,
  5,
  3038,
  19,
  87,
  220,
  50,
  3,
  41,
  49,
  7,
  1289,
  8,
  615,
  1226],
 [14726,
  52,
  1290,
  2730,
  14727,
  9,
  81,
  200,
  1674,
  3,
  1125,
  1790,
  3,
  2,
  1079,
  1227,
  10,
  426],
 [2,
  1006,
  124,
  2,
  60,
  854,
  5,
  23,
  6228,
  2071,
  1006,
  419,
  124,
  9,
  10639,
  31,
  14728,
  1408,
  807,
  5,
  2,
  14729],
 [2,
  1080,
  855,
  3022,
  2731,
  2,
  10640,
  14730,
  31,
  2,
  2867,
  5,
  14731,
  38,
  9,
  14732,
  33,
  131,
  18,
  180,
  8,
  2,
  3662,
  5,
  2,
  3915,
  649],
 [2,
  6229,
  1202,
  5,
  2,
  14733,
  1848,
  8469,
  30,
  3433,
  124,
  2,
  111,
  740,
  305,
  3434,
  33,
  5554,
  124,
  13,
  4967,
  136,
  7,
  2,
  10641,
  322],
 [2,
  3657,
  1491,
  1487,
  3,
  479,
  918,
  26,
  4,
  687,
  1911,
  1080,
  5,
  479,
  521,
  7,
  1573,
  21,
  44,
  275,
  315,
  138,
  2,
  6230,
  3,
  245,
  8,
  1204],
 [14734,
  14735,
  63,
  2246,
  3,
  3042,
  2247,
  2868,
  6,
  7135,
  14736,
  3909,
  115,
  8470,
  23,
  8471,
  388,
  21,
  23,
  2591,
  59,
  51,
  13,
  60,
  1448,
  8,
  522,
  2,
  4551],
 [72,
  75,
  8472,
  9,
  14737,
  66,
  515,
  2592,
  5,
  3043,
  244,
  1205,
  14738,
  6,
  7136,
  5,
  10642,
  3663,
  24,
  2869,
  87,
  25,
  8,
  34],
 [2,
  8473,
  13,
  631,
  33,
  10643,
  8,
  369,
  352,
  344,
  487,
  23,
  1449,
  2870,
  5,
  37,
  10644,
  10645,
  180],
 [2, 14739, 341, 4, 8474, 135, 1411, 4, 3220],
 [2,
  1987,
  594,
  4968,
  9,
  2871,
  4,
  4552,
  8475,
  11,
  122,
  102,
  1262,
  94,
  2,
  14740,
  1843,
  1407],
 [2,
  14741,
  30,
  2156,
  34,
  2157,
  837,
  2731,
  10,
  1492,
  91,
  4,
  714,
  190,
  605,
  222,
  14742,
  54,
  465,
  3,
  2158,
  4,
  1263,
  8476,
  3,
  117,
  16,
  258],
 [2,
  3221,
  1679,
  2072,
  856,
  84,
  27,
  6,
  15,
  3044,
  158,
  32,
  1050,
  62,
  3435,
  10646,
  18,
  2,
  2159],
 [2,
  3915,
  14743,
  85,
  306,
  200,
  2348,
  369,
  248,
  207,
  118,
  533,
  19,
  1228,
  3,
  1849,
  2,
  4216,
  10,
  2248],
 [2,
  169,
  9,
  2872,
  3,
  14744,
  1793,
  7,
  527,
  5,
  103,
  27,
  602,
  36,
  477,
  10647,
  3,
  3435,
  1100,
  631,
  18,
  15,
  374,
  2458],
 [128,
  17,
  2,
  786,
  4969,
  7,
  2,
  129,
  1101,
  8477,
  12,
  7,
  360,
  3,
  2,
  678,
  28,
  1912,
  334,
  1028,
  1100,
  18,
  15,
  1051,
  4553],
 [1374,
  8478,
  43,
  311,
  91,
  2,
  222,
  38,
  2073,
  142,
  5,
  3664,
  388,
  120,
  452,
  2732,
  7,
  15,
  316,
  715],
 [73, 41, 346, 39, 265, 8, 103, 107, 625, 4554, 716, 230],
 [922,
  14745,
  106,
  17,
  109,
  1229,
  594,
  4217,
  11,
  515,
  2074,
  14,
  7137,
  3201,
  10648],
 [2733,
  155,
  3,
  757,
  53,
  1291,
  14746,
  249,
  29,
  2,
  8469,
  2459,
  1576,
  12,
  39,
  2,
  60,
  2249,
  13,
  14747],
 [14748,
  38,
  18,
  41,
  711,
  1375,
  21,
  4,
  89,
  68,
  231,
  790,
  9,
  12,
  3,
  20,
  4970,
  27,
  14749,
  18,
  4,
  1028,
  520,
  2160,
  94,
  2,
  547,
  212],
 [2250,
  40,
  902,
  4,
  534,
  266,
  1292,
  50,
  3,
  2,
  295,
  2251,
  7,
  1538,
  31,
  2,
  2593,
  398,
  4555,
  443,
  33,
  4218,
  14750],
 [3222,
  14,
  14751,
  3663,
  14752,
  14753,
  444,
  14754,
  455,

In [20]:
input_sequences = []
for seq in df:
    if len(seq)<2:
        continue
    for i in range(1, len(seq)):
        ngram = seq[:i+1]
        input_sequences.append(ngram)

In [21]:
input_sequences

[[151, 377],
 [151, 377, 12],
 [151, 377, 12, 16],
 [151, 377, 12, 16, 9],
 [151, 377, 12, 16, 9, 159],
 [151, 377, 12, 16, 9, 159, 580],
 [151, 377, 12, 16, 9, 159, 580, 3],
 [151, 377, 12, 16, 9, 159, 580, 3, 5525],
 [151, 377, 12, 16, 9, 159, 580, 3, 5525, 365],
 [151, 377, 12, 16, 9, 159, 580, 3, 5525, 365, 1719],
 [151, 377, 12, 16, 9, 159, 580, 3, 5525, 365, 1719, 69],
 [151, 377, 12, 16, 9, 159, 580, 3, 5525, 365, 1719, 69, 2574],
 [151, 377, 12, 16, 9, 159, 580, 3, 5525, 365, 1719, 69, 2574, 50],
 [151, 377, 12, 16, 9, 159, 580, 3, 5525, 365, 1719, 69, 2574, 50, 14],
 [151, 377, 12, 16, 9, 159, 580, 3, 5525, 365, 1719, 69, 2574, 50, 14, 2],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36,
  14612],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36,
  14612,
  2],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36,
  14612,
  2,
  55],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36,
  14612,
  2,
  55,
  56],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36,
  14612,
  2,
  55,
  56,
  1482],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36,
  14612,
  2,
  55,
  56,
  1482,
  8],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36,
  14612,
  2,
  55,
  56,
  1482,
  8,
  2],
 [151,
  377,
  12,
  16,
  9,
  159,
  580,
  3,
  5525,
  365,
  1719,
  69,
  2574,
  50,
  14,
  2,
  14611,
  207,
  4189,
  5,
  2,
  36,
  14612,
  2,
  55,
  56,
  1482,
  8,
  2,
  853],
 [19, 13],
 [19, 13, 14613],
 [19, 13, 14613, 33],
 [19, 13, 14613, 33, 2339],
 [19, 13, 14613, 33, 2339, 6],
 [19, 13, 14613, 33, 2339, 6, 2340],
 [19, 13, 14613, 33, 2339, 6, 2340, 59],
 [19, 13, 14613, 33, 2339, 6, 2340, 59, 19],
 [19, 13, 14613, 33, 2339, 6, 2340, 59, 19, 1975],
 [19, 13, 14613, 33, 2339, 6, 2340, 59, 19, 1975, 3],
 [19, 13, 14613, 33, 2339, 6, 2340, 59, 19, 1975, 3, 2],
 [19, 13, 14613, 33, 2339, 6, 2340, 59, 19, 1975, 3, 2, 108],
 [19, 13, 14613, 33, 2339, 6, 2340, 59, 19, 1975, 3, 2, 108, 5],
 [19, 13, 14613, 33, 2339, 6, 2340, 59, 19, 1975, 3, 2, 108, 5, 2],
 [19, 13, 14613, 33, 2339, 6, 2340, 59, 19, 1975, 3, 2, 108, 5, 2, 3419],
 [19, 13, 14613, 33, 2339, 6, 2340, 59, 19, 1975, 3, 2, 108, 5, 2, 3419, 39],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3,
  2],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3,
  2,
  55],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3,
  2,
  55,
  56],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3,
  2,
  55,
  56,
  8429],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3,
  2,
  55,
  56,
  8429,
  262],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3,
  2,
  55,
  56,
  8429,
  262,
  7],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3,
  2,
  55,
  56,
  8429,
  262,
  7,
  895],
 [19,
  13,
  14613,
  33,
  2339,
  6,
  2340,
  59,
  19,
  1975,
  3,
  2,
  108,
  5,
  2,
  3419,
  39,
  2,
  3892,
  251,
  3,
  2,
  55,
  56,
  8429,
  262,
  7,
  895,
  987],
 [509, 34],
 [509, 34, 20],
 [509, 34, 20, 4],
 [509, 34, 20, 4, 1406],
 [509, 34, 20, 4, 1406, 34],
 [509, 34, 20, 4, 1406, 34, 195],
 [509, 34, 20, 4, 1406, 34, 195, 1367],
 [509, 34, 20, 4, 1406, 34, 195, 1367, 58],
 [509, 34, 20, 4, 1406, 34, 195, 1367, 58, 87],
 [509, 34, 20, 4, 1406, 34, 195, 1367, 58, 87, 25],
 [509, 34, 20, 4, 1406, 34, 195, 1367, 58, 87, 25, 8430],
 [3893, 286],
 [3893, 286, 3894],
 [3893, 286, 3894, 50],
 [3893, 286, 3894, 50, 10574],
 [3893, 286, 3894, 50, 10574, 10],
 [3893, 286, 3894, 50, 10574, 10, 79],
 [3893, 286, 3894, 50, 10574, 10, 79, 14614],
 [3893, 286, 3894, 50, 10574, 10, 79, 14614, 14615],
 [3893, 286, 3894, 50, 10574, 10, 79, 14614, 14615, 6],
 [3893, 286, 3894, 50, 10574, 10, 79, 14614, 14615, 6, 19],
 [3893, 286, 3894, 50, 10574, 10, 79, 14614, 14615, 6, 19, 10575],
 [3893, 286, 3894, 50, 10574, 10, 79, 14614, 14615, 6, 19, 10575, 67],
 [3893, 286, 3894, 50, 10574, 10, 79, 14614, 14615, 6, 19, 10575, 67, 30],
 [3893, 286, 3894, 50, 10574, 10, 79, 14614, 14615, 6, 19, 10575, 67, 30, 13],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201,
  14],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201,
  14,
  4],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201,
  14,
  4,
  1117],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201,
  14,
  4,
  1117,
  14616],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201,
  14,
  4,
  1117,
  14616,
  10576],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201,
  14,
  4,
  1117,
  14616,
  10576,
  7],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201,
  14,
  4,
  1117,
  14616,
  10576,
  7,
  14617],
 [3893,
  286,
  3894,
  50,
  10574,
  10,
  79,
  14614,
  14615,
  6,
  19,
  10575,
  67,
  30,
  13,
  3420,
  15,
  3201,
  14,
  4,
  1117,
  14616,
  10576,
  7,
  14617,
  7100],
 [1902, 3021],
 [1902, 3021, 142],
 [1902, 3021, 142, 3895],
 [1902, 3021, 142, 3895, 1528],
 [1902, 3021, 142, 3895, 1528, 5526],
 [1902, 3021, 142, 3895, 1528, 5526, 14618],
 [1902, 3021, 142, 3895, 1528, 5526, 14618, 5],
 [1902, 3021, 142, 3895, 1528, 5526, 14618, 5, 8431],
 [1902, 3021, 142, 3895, 1528, 5526, 14618, 5, 8431, 2575],
 [1902, 3021, 142, 3895, 1528, 5526, 14618, 5, 8431, 2575, 37],
 [1902, 3021, 142, 3895, 1528, 5526, 14618, 5, 8431, 2575, 37, 6],
 [1902, 3021, 142, 3895, 1528, 5526, 14618, 5, 8431, 2575, 37, 6, 10577],
 [1902, 3021, 142, 3895, 1528, 5526, 14618, 5, 8431, 2575, 37, 6, 10577, 37],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39,
  218],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39,
  218,
  5],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39,
  218,
  5,
  2],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39,
  218,
  5,
  2,
  1253],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39,
  218,
  5,
  2,
  1253,
  896],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39,
  218,
  5,
  2,
  1253,
  896,
  2055],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39,
  218,
  5,
  2,
  1253,
  896,
  2055,
  366],
 [1902,
  3021,
  142,
  3895,
  1528,
  5526,
  14618,
  5,
  8431,
  2575,
  37,
  6,
  10577,
  37,
  4,
  803,
  39,
  218,
  5,
  2,
  1253,
  896,
  2055,
  366,
  866],
 [2, 4190],
 [2, 4190, 49],
 [2, 4190, 49, 98],
 [2, 4190, 49, 98, 204],
 [2, 4190, 49, 98, 204, 13],
 [2, 4190, 49, 98, 204, 13, 541],
 [2, 4190, 49, 98, 204, 13, 541, 389],
 [2, 4190, 49, 98, 204, 13, 541, 389, 18],
 [2, 4190, 49, 98, 204, 13, 541, 389, 18, 2],
 [2, 4190, 49, 98, 204, 13, 541, 389, 18, 2, 432],
 [2, 4190, 49, 98, 204, 13, 541, 389, 18, 2, 432, 1117],
 [2, 4190, 49, 98, 204, 13, 541, 389, 18, 2, 432, 1117, 1529],
 [2, 4190, 49, 98, 204, 13, 541, 389, 18, 2, 432, 1117, 1529, 10],
 [2, 4190, 49, 98, 204, 13, 541, 389, 18, 2, 432, 1117, 1529, 10, 673],
 [2, 4190, 49, 98, 204, 13, 541, 389, 18, 2, 432, 1117, 1529, 10, 673, 51],
 [2, 4190, 49, 98, 204, 13, 541, 389, 18, 2, 432, 1117, 1529, 10, 673, 51, 13],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322,
  39],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322,
  39,
  37],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322,
  39,
  37,
  189],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322,
  39,
  37,
  189,
  382],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322,
  39,
  37,
  189,
  382,
  37],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322,
  39,
  37,
  189,
  382,
  37,
  916],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322,
  39,
  37,
  189,
  382,
  37,
  916,
  433],
 [2,
  4190,
  49,
  98,
  204,
  13,
  541,
  389,
  18,
  2,
  432,
  1117,
  1529,
  10,
  673,
  51,
  13,
  216,
  442,
  322,
  39,
  37,
  189,
  382,
  37,
  916,
  433,
  12],
 [1285, 11],
 [1285, 11, 485],
 [1285, 11, 485, 34],
 [1285, 11, 485, 34, 23],
 [1285, 11, 485, 34, 23, 945],
 [1285, 11, 485, 34, 23, 945, 8],
 [1285, 11, 485, 34, 23, 945, 8, 36],
 [1285, 11, 485, 34, 23, 945, 8, 36, 7101],
 [1285, 11, 485, 34, 23, 945, 8, 36, 7101, 14619],
 [1285, 11, 485, 34, 23, 945, 8, 36, 7101, 14619, 300],
 [1285, 11, 485, 34, 23, 945, 8, 36, 7101, 14619, 300, 1218],
 [1285, 11, 485, 34, 23, 945, 8, 36, 7101, 14619, 300, 1218, 1976],
 [1285, 11, 485, 34, 23, 945, 8, 36, 7101, 14619, 300, 1218, 1976, 3896],
 [1285, 11, 485, 34, 23, 945, 8, 36, 7101, 14619, 300, 1218, 1976, 3896, 21],
 [1285,
  11,
  485,
  34,
  23,
  945,
  8,
  36,
  7101,
  14619,
  300,
  1218,
  1976,
  3896,
  21,
  51],
 [1285,
  11,
  485,
  34,
  23,
  945,
  8,
  36,
  7101,
  14619,
  300,
  1218,
  1976,
  3896,
  21,
  51,
  3202],
 [1285,
  11,
  485,
  34,
  23,
  945,
  8,
  36,
  7101,
  14619,
  300,
  1218,
  1976,
  3896,
  21,
  51,
  3202,
  50],
 [1285,
  11,
  485,
  34,
  23,
  945,
  8,
  36,
  7101,
  14619,
  300,
  1218,
  1976,
  3896,
  21,
  51,
  3202,
  50,
  23],
 [1285,
  11,
  485,
  34,
  23,
  945,
  8,
  36,
  7101,
  14619,
  300,
  1218,
  1976,
  3896,
  21,
  51,
  3202,
  50,
  23,
  486],
 [44, 61],
 [44, 61, 687],
 [44, 61, 687, 4],
 [44, 61, 687, 4, 207],
 [44, 61, 687, 4, 207, 42],
 [44, 61, 687, 4, 207, 42, 2715],
 [44, 61, 687, 4, 207, 42, 2715, 252],
 [44, 61, 687, 4, 207, 42, 2715, 252, 585],
 [44, 61, 687, 4, 207, 42, 2715, 252, 585, 520],
 [44, 61, 687, 4, 207, 42, 2715, 252, 585, 520, 160],
 [44, 61, 687, 4, 207, 42, 2715, 252, 585, 520, 160, 205],
 [44, 61, 687, 4, 207, 42, 2715, 252, 585, 520, 160, 205, 39],
 [44, 61, 687, 4, 207, 42, 2715, 252, 585, 520, 160, 205, 39, 2],
 [44, 61, 687, 4, 207, 42, 2715, 252, 585, 520, 160, 205, 39, 2, 1006],
 [44, 61, 687, 4, 207, 42, 2715, 252, 585, 520, 160, 205, 39, 2, 1006, 4943],
 [44,
  61,
  687,
  4,
  207,
  42,
  2715,
  252,
  585,
  520,
  160,
  205,
  39,
  2,
  1006,
  4943,
  2],
 [44,
  61,
  687,
  4,
  207,
  42,
  2715,
  252,
  585,
  520,
  160,
  205,
  39,
  2,
  1006,
  4943,
  2,
  55],
 [44,
  61,
  687,
  4,
  207,
  42,
  2715,
  252,
  585,
  520,
  160,
  205,
  39,
  2,
  1006,
  4943,
  2,
  55,
  56],
 [44,
  61,
  687,
  4,
  207,
  42,
  2715,
  252,
  585,
  520,
  160,
  205,
  39,
  2,
  1006,
  4943,
  2,
  55,
  56,
  2716],
 [7, 14620],
 [7, 14620, 240],
 [7, 14620, 240, 14621],
 [7, 14620, 240, 14621, 5527],
 [7, 14620, 240, 14621, 5527, 4524],
 [7, 14620, 240, 14621, 5527, 4524, 498],
 [7, 14620, 240, 14621, 5527, 4524, 498, 10578],
 [7, 14620, 240, 14621, 5527, 4524, 498, 10578, 14],
 [7, 14620, 240, 14621, 5527, 4524, 498, 10578, 14, 2],
 [7, 14620, 240, 14621, 5527, 4524, 498, 10578, 14, 2, 1368],
 [7, 14620, 240, 14621, 5527, 4524, 498, 10578, 14, 2, 1368, 5],
 [7, 14620, 240, 14621, 5527, 4524, 498, 10578, 14, 2, 1368, 5, 8432],
 [7, 14620, 240, 14621, 5527, 4524, 498, 10578, 14, 2, 1368, 5, 8432, 6],
 [7, 14620, 240, 14621, 5527, 4524, 498, 10578, 14, 2, 1368, 5, 8432, 6, 5528],
 [7,
  14620,
  240,
  14621,
  5527,
  4524,
  498,
  10578,
  14,
  2,
  1368,
  5,
  8432,
  6,
  5528,
  3],
 [7,
  14620,
  240,
  14621,
  5527,
  4524,
  498,
  10578,
  14,
  2,
  1368,
  5,
  8432,
  6,
  5528,
  3,
  395],
 [7,
  14620,
  240,
  14621,
  5527,
  4524,
  498,
  10578,
  14,
  2,
  1368,
  5,
  8432,
  6,
  5528,
  3,
  395,
  4],
 [7,
  14620,
  240,
  14621,
  5527,
  4524,
  498,
  10578,
  14,
  2,
  1368,
  5,
  8432,
  6,
  5528,
  3,
  395,
  4,
  44],
 [7,
  14620,
  240,
  14621,
  5527,
  4524,
  498,
  10578,
  14,
  2,
  1368,
  5,
  8432,
  6,
  5528,
  3,
  395,
  4,
  44,
  6191],
 [7,
  14620,
  240,
  14621,
  5527,
  4524,
  498,
  10578,
  14,
  2,
  1368,
  5,
  8432,
  6,
  5528,
  3,
  395,
  4,
  44,
  6191,
  629],
 [7,
  14620,
  240,
  14621,
  5527,
  4524,
  498,
  10578,
  14,
  2,
  1368,
  5,
  8432,
  6,
  5528,
  3,
  395,
  4,
  44,
  6191,
  629,
  304],
 [89, 68],
 [89, 68, 157],
 [89, 68, 157, 83],
 [89, 68, 157, 83, 2],
 [89, 68, 157, 83, 2, 14622],
 [89, 68, 157, 83, 2, 14622, 5],
 [89, 68, 157, 83, 2, 14622, 5, 2],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196, 946],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196, 946, 3],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196, 946, 3, 2],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196, 946, 3, 2, 55],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196, 946, 3, 2, 55, 1096],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196, 946, 3, 2, 55, 1096, 24],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196, 946, 3, 2, 55, 1096, 24, 49],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196, 946, 3, 2, 55, 1096, 24, 49, 40],
 [89, 68, 157, 83, 2, 14622, 5, 2, 196, 946, 3, 2, 55, 1096, 24, 49, 40, 25],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581,
  14623],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581,
  14623,
  5529],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581,
  14623,
  5529,
  5],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581,
  14623,
  5529,
  5,
  355],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581,
  14623,
  5529,
  5,
  355,
  6],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581,
  14623,
  5529,
  5,
  355,
  6,
  88],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581,
  14623,
  5529,
  5,
  355,
  6,
  88,
  2850],
 [89,
  68,
  157,
  83,
  2,
  14622,
  5,
  2,
  196,
  946,
  3,
  2,
  55,
  1096,
  24,
  49,
  40,
  25,
  4,
  581,
  14623,
  5529,
  5,
  355,
  6,
  88,
  2850,
  259],
 [8433, 22],
 [8433, 22, 246],
 [8433, 22, 246, 247],
 [8433, 22, 246, 247, 1097],
 [8433, 22, 246, 247, 1097, 26],
 [8433, 22, 246, 247, 1097, 26, 396],
 [8433, 22, 246, 247, 1097, 26, 396, 1671],
 [8433, 22, 246, 247, 1097, 26, 396, 1671, 1977],
 [8433, 22, 246, 247, 1097, 26, 396, 1671, 1977, 14624],
 [8433, 22, 246, 247, 1097, 26, 396, 1671, 1977, 14624, 38],
 [8433, 22, 246, 247, 1097, 26, 396, 1671, 1977, 14624, 38, 143],
 [8433, 22, 246, 247, 1097, 26, 396, 1671, 1977, 14624, 38, 143, 3],
 [8433, 22, 246, 247, 1097, 26, 396, 1671, 1977, 14624, 38, 143, 3, 256],
 [8433, 22, 246, 247, 1097, 26, 396, 1671, 1977, 14624, 38, 143, 3, 256, 4],
 [8433,
  22,
  246,
  247,
  1097,
  26,
  396,
  1671,
  1977,
  14624,
  38,
  143,
  3,
  256,
  4,
  611],
 [8433,
  22,
  246,
  247,
  1097,
  26,
  396,
  1671,
  1977,
  14624,
  38,
  143,
  3,
  256,
  4,
  611,
  217],
 [8433,
  22,
  246,
  247,
  1097,
  26,
  396,
  1671,
  1977,
  14624,
  38,
  143,
  3,
  256,
  4,
  611,
  217,
  144],
 [8433,
  22,
  246,
  247,
  1097,
  26,
  396,
  1671,
  1977,
  14624,
  38,

In [22]:
max_len = max([len(i) for i in input_sequences])

In [23]:
max_len

44

In [24]:
input=pad_sequences(input_sequences, maxlen=max_len, padding='pre')

In [25]:
input

array([[   0,    0,    0, ...,    0,  151,  377],
       [   0,    0,    0, ...,  151,  377,   12],
       [   0,    0,    0, ...,  377,   12,   16],
       ...,
       [   0,    0,    0, ..., 1450,   10,   85],
       [   0,    0,    0, ...,   10,   85, 2007],
       [   0,    0,    0, ...,   85, 2007, 1317]], dtype=int32)

In [26]:
X=input[:,:-1]
y=input[:,-1]

In [27]:
X[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 151], dtype=int32)

In [28]:
X.shape

(346567, 43)

In [29]:
y.shape

(346567,)

In [30]:
y=np.array(y)

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
X_train.shape

(277253, 43)

In [34]:
vocab_size = len(tokenizer.word_index) + 1

In [35]:
vocab_size

28448

In [36]:
max_len=X.shape[1]

In [37]:
max_len

43

In [38]:
model = Sequential([
    Embedding(vocab_size, 128, input_length=max_len),
    LSTM(256),
    Dense(vocab_size, activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [39]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
model.build(input_shape=(None, max_len))

In [41]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 43, 128)        │     3,641,344 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 28448)          │     7,311,136 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,346,720 (43.28 MB)

 Trainable params: 11,346,720 (43.28 MB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test))

Epoch 1/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 140s 16ms/step - accuracy: 0.4948 - loss: 2.5256 - val_accuracy: 0.1178 - val_loss: 8.1289
Epoch 2/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.5285 - loss: 2.3212 - val_accuracy: 0.1159 - val_loss: 8.3107
Epoch 3/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 143s 16ms/step - accuracy: 0.5598 - loss: 2.1506 - val_accuracy: 0.1102 - val_loss: 8.4919
Epoch 4/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.5851 - loss: 2.0042 - val_accuracy: 0.1093 - val_loss: 8.6500
Epoch 5/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.6062 - loss: 1.8850 - val_accuracy: 0.1083 - val_loss: 8.8062
Epoch 6/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.6249 - loss: 1.7835 - val_accuracy: 0.1081 - val_loss: 8.9635
Epoch 7/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.6412 - loss: 1.6951 - val_accuracy: 0.1053 - val_loss: 9.1047
Epoch 8/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.6555 - loss: 1.6209 - val_accuracy: 0.1052 - val_loss: 9.2222
Epoch 9/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 147s 17ms/step - accuracy: 0.6662 - loss: 1.5572 - val_accuracy: 0.1032 - val_loss: 9.3755
Epoch 10/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 143s 16ms/step - accuracy: 0.6744 - loss: 1.5059 - val_accuracy: 0.1014 - val_loss: 9.5125
Epoch 11/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.6844 - loss: 1.4561 - val_accuracy: 0.1012 - val_loss: 9.6191
Epoch 12/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.6911 - loss: 1.4171 - val_accuracy: 0.0994 - val_loss: 9.7328
Epoch 13/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.6977 - loss: 1.3803 - val_accuracy: 0.0995 - val_loss: 9.8393
Epoch 14/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.7038 - loss: 1.3469 - val_accuracy: 0.1010 - val_loss: 9.9443
Epoch 15/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.7080 - loss: 1.3205 - val_accuracy: 0.0984 - val_loss: 10.0497
Epoch 16/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.7099 - loss: 1.3044 - val_accuracy: 0.0990 - val_loss: 10.1320
Epoch 17/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7135 - loss: 1.2834 - val_accuracy: 0.0992 - val_loss: 10.2078
Epoch 18/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.7164 - loss: 1.2669 - val_accuracy: 0.0971 - val_loss: 10.2963
Epoch 19/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.7189 - loss: 1.2531 - val_accuracy: 0.0974 - val_loss: 10.3843
Epoch 20/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 141s 16ms/step - accuracy: 0.7214 - loss: 1.2379 - val_accuracy: 0.0979 - val_loss: 10.4472
Epoch 21/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7219 - loss: 1.2301 - val_accuracy: 0.0959 - val_loss: 10.5018
Epoch 22/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 143s 16ms/step - accuracy: 0.7241 - loss: 1.2190 - val_accuracy: 0.0979 - val_loss: 10.5857
Epoch 23/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7237 - loss: 1.2143 - val_accuracy: 0.0978 - val_loss: 10.6279
Epoch 24/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7256 - loss: 1.2032 - val_accuracy: 0.0964 - val_loss: 10.6911
Epoch 25/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7258 - loss: 1.2018 - val_accuracy: 0.0979 - val_loss: 10.7666
Epoch 26/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7250 - loss: 1.1970 - val_accuracy: 0.0962 - val_loss: 10.8152
Epoch 27/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7258 - loss: 1.1930 - val_accuracy: 0.0959 - val_loss: 10.8854
Epoch 28/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7238 - loss: 1.1951 - val_accuracy: 0.0953 - val_loss: 10.9147
Epoch 29/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7240 - loss: 1.1923 - val_accuracy: 0.0946 - val_loss: 10.9707
Epoch 30/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7249 - loss: 1.1917 - val_accuracy: 0.0962 - val_loss: 10.9986
Epoch 31/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 201s 16ms/step - accuracy: 0.7247 - loss: 1.1868 - val_accuracy: 0.0951 - val_loss: 11.0464
Epoch 32/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7240 - loss: 1.1887 - val_accuracy: 0.0949 - val_loss: 11.1004
Epoch 33/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7225 - loss: 1.1896 - val_accuracy: 0.0956 - val_loss: 11.1278
Epoch 34/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7229 - loss: 1.1903 - val_accuracy: 0.0967 - val_loss: 11.1773
Epoch 35/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7213 - loss: 1.1950 - val_accuracy: 0.0938 - val_loss: 11.1967
Epoch 36/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7199 - loss: 1.1949 - val_accuracy: 0.0935 - val_loss: 11.2319
Epoch 37/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7194 - loss: 1.1981 - val_accuracy: 0.0943 - val_loss: 11.2802
Epoch 38/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7184 - loss: 1.1978 - val_accuracy: 0.0946 - val_loss: 11.2760
Epoch 39/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7176 - loss: 1.2012 - val_accuracy: 0.0953 - val_loss: 11.3256
Epoch 40/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7155 - loss: 1.2107 - val_accuracy: 0.0948 - val_loss: 11.3415
Epoch 41/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7149 - loss: 1.2100 - val_accuracy: 0.0943 - val_loss: 11.3410
Epoch 42/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 143s 16ms/step - accuracy: 0.7159 - loss: 1.2069 - val_accuracy: 0.0961 - val_loss: 11.4035
Epoch 43/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7138 - loss: 1.2101 - val_accuracy: 0.0955 - val_loss: 11.4473
Epoch 44/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7137 - loss: 1.2114 - val_accuracy: 0.0950 - val_loss: 11.4554
Epoch 45/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7119 - loss: 1.2193 - val_accuracy: 0.0953 - val_loss: 11.4724
Epoch 46/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7098 - loss: 1.2245 - val_accuracy: 0.0934 - val_loss: 11.4994
Epoch 47/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7090 - loss: 1.2291 - val_accuracy: 0.0942 - val_loss: 11.5173
Epoch 48/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7065 - loss: 1.2356 - val_accuracy: 0.0956 - val_loss: 11.5244
Epoch 49/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7070 - loss: 1.2327 - val_accuracy: 0.0966 - val_loss: 11.5590
Epoch 50/50
8665/8665 ━━━━━━━━━━━━━━━━━━━━ 142s 16ms/step - accuracy: 0.7055 - loss: 1.2395 - val_accuracy: 0.0956 - val_loss: 11.5672

In [46]:
model.save('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [47]:
import pickle
with open('tokenizer.pkl', 'wb') as file:
    pickle.dump(tokenizer, file)