In [1]:
import pandas as pd

In [2]:
df=pd.read_json('News_Category_Dataset_v3.json', lines=True)

In [3]:
df.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

In [4]:
df.shape

(209527, 6)

In [5]:
df.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='object')

In [6]:
df=df[['short_description']].head(10000)

In [7]:
df

                                      short_description
0     Health experts said it is too early to predict...
1     He was subdued by passengers and crew when he ...
2     "Until you have a dog you don't understand wha...
3     "Accidentally put grown-up toothpaste on my to...
4     Amy Cooper accused investment firm Franklin Te...
...                                                 ...
9995  Dr. Robert Redfield, who was hired in March, w...
9996  The ad was supposed to help Wisconsin GOP Sena...
9997                          We're still stressed out.
9998  Among other happenings, the first fast-food un...
9999  You'll be able to stop Facebook from linking b...

[10000 rows x 1 columns]

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.shape

(9995, 1)

In [11]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [13]:
tokenizer = Tokenizer(oov_token='<OOV>')

In [18]:
tokenizer.fit_on_texts(df['short_description'])

In [19]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'to': 3,
 'a': 4,
 'of': 5,
 'and': 6,
 'in': 7,
 'for': 8,
 'on': 9,
 'said': 10,
 'is': 11,
 'that': 12,
 'was': 13,
 'with': 14,
 'his': 15,
 'at': 16,
 'as': 17,
 'president': 18,
 'has': 19,
 'from': 20,
 'he': 21,
 'an': 22,
 'it': 23,
 'are': 24,
 'have': 25,
 'after': 26,
 'trump': 27,
 'be': 28,
 'new': 29,
 'her': 30,
 '”': 31,
 'about': 32,
 'by': 33,
 'who': 34,
 'will': 35,
 'this': 36,
 'but': 37,
 'not': 38,
 'people': 39,
 'one': 40,
 'you': 41,
 'their': 42,
 'more': 43,
 'year': 44,
 'u': 45,
 'former': 46,
 'been': 47,
 's': 48,
 'were': 49,
 'out': 50,
 'i': 51,
 'they': 52,
 'up': 53,
 'she': 54,
 'over': 55,
 'house': 56,
 'had': 57,
 'what': 58,
 'two': 59,
 'into': 60,
 'first': 61,
 'during': 62,
 'when': 63,
 'all': 64,
 'host': 65,
 'than': 66,
 'state': 67,
 'show': 68,
 'some': 69,
 'we': 70,
 'also': 71,
 'or': 72,
 'last': 73,
 'just': 74,
 'no': 75,
 'against': 76,
 'police': 77,
 'its': 78,
 'your': 79,
 'how': 80,
 'would': 81,
 'old': 82,
 'if': 83,
 'time': 84,
 'could': 85,
 'star': 86,
 'coronavirus': 87,
 'white': 88,
 'donald': 89,
 'covid': 90,
 'say': 91,
 '19': 92,
 'told': 93,
 'can': 94,
 'now': 95,
 'like': 96,
 'which': 97,
 "trump's": 98,
 'day': 99,
 '—': 100,
 'other': 101,
 "it's": 102,
 'so': 103,
 'him': 104,
 'says': 105,
 'actor': 106,
 'republican': 107,
 'news': 108,
 'back': 109,
 'week': 110,
 'years': 111,
 'late': 112,
 'made': 113,
 'biden': 114,
 'pandemic': 115,
 'get': 116,
 'while': 117,
 'before': 118,
 'my': 119,
 'called': 120,
 'black': 121,
 'do': 122,
 'officials': 123,
 'being': 124,
 'health': 125,
 'man': 126,
 'may': 127,
 'democratic': 128,
 'off': 129,
 'most': 130,
 'even': 131,
 'country': 132,
 'court': 133,
 'these': 134,
 'election': 135,
 'there': 136,
 'our': 137,
 'since': 138,
 'home': 139,
 'world': 140,
 'make': 141,
 'york': 142,
 '000': 143,
 "president's": 144,
 'them': 145,
 'right': 146,
 'gop': 147,
 'campaign': 148,
 'killed': 149,
 'twitter': 150,
 'only': 151,
 'down': 152,
 'fox': 153,
 'wrote': 154,
 'joe': 155,
 'know': 156,
 'american': 157,
 'federal': 158,
 'three': 159,
 'still': 160,
 'women': 161,
 'attack': 162,
 'city': 163,
 'public': 164,
 'many': 165,
 'attorney': 166,
 'accused': 167,
 'national': 168,
 'video': 169,
 'help': 170,
 'found': 171,
 'want': 172,
 'government': 173,
 'school': 174,
 'law': 175,
 'me': 176,
 'sunday': 177,
 'media': 178,
 'days': 179,
 'death': 180,
 'million': 181,
 'life': 182,
 'should': 183,
 'least': 184,
 'face': 185,
 'way': 186,
 'died': 187,
 'administration': 188,
 'singer': 189,
 'according': 190,
 'take': 191,
 'got': 192,
 'family': 193,
 'reportedly': 194,
 'long': 195,
 'much': 196,
 'social': 197,
 'did': 198,
 'because': 199,
 'night': 200,
 'bill': 201,
 'work': 202,
 'rights': 203,
 'took': 204,
 'children': 205,
 'senator': 206,
 'own': 207,
 'leader': 208,
 'where': 209,
 'california': 210,
 'including': 211,
 'senate': 212,
 'democrats': 213,
 'justice': 214,
 'shot': 215,
 'around': 216,
 'go': 217,
 'look': 218,
 'asked': 219,
 'under': 220,
 '“the': 221,
 'political': 222,
 'hit': 223,
 'good': 224,
 '2020': 225,
 'secretary': 226,
 'care': 227,
 'states': 228,
 'group': 229,
 'presidential': 230,
 'month': 231,
 'authorities': 232,
 'next': 233,
 'end': 234,
 'investigation': 235,
 'change': 236,
 'between': 237,
 'latest': 238,
 'going': 239,
 'republicans': 240,
 'too': 241,
 'woman': 242,
 "here's": 243,
 'monday': 244,
 'without': 245,
 'top': 246,
 'used': 247,
 'north': 248,
 "don't": 249,
 'support': 250,
 'set': 251,
 'general': 252,
 'fire': 253,
 'why': 254,
 'official': 255,
 '“i': 256,
 'experts': 257,
 'us': 258,
 'part': 259,
 '1': 260,
 'texas': 261,
 'gov': 262,
 'put': 263,
 'reported': 264,
 'comes': 265,
 'big': 266,
 'person': 267,
 'deal': 268,
 'rep': 269,
 'office': 270,
 'second': 271,
 'americans': 272,
 'think': 273,
 'decision': 274,
 'through': 275,
 'russian': 276,
 'case': 277,
 'shooting': 278,
 'need': 279,
 'any': 280,
 'went': 281,
 '6': 282,
 'anti': 283,
 'high': 284,
 'security': 285,
 'sen': 286,
 'series': 287,
 'post': 288,
 'it’s': 289,
 'shows': 290,
 'ukraine': 291,
 'vote': 292,
 'nearly': 293,
 'power': 294,
 'governor': 295,
 '10': 296,
 'military': 297,
 'co': 298,
 'those': 299,
 'never': 300,
 'left': 301,
 'history': 302,
 'capitol': 303,
 'best': 304,
 'both': 305,
 'congress': 306,
 'far': 307,
 'washington': 308,
 'war': 309,
 'supreme': 310,
 'times': 311,
 'four': 312,
 'five': 313,
 'use': 314,
 'another': 315,
 'amid': 316,
 'away': 317,
 'party': 318,
 'thousands': 319,
 'saturday': 320,
 'sexual': 321,
 'whether': 322,
 'response': 323,
 'report': 324,
 'vice': 325,
 'weeks': 326,
 'director': 327,
 'department': 328,
 "he's": 329,
 'company': 330,
 'michael': 331,
 'came': 332,
 'florida': 333,
 'claims': 334,
 'members': 335,
 'very': 336,
 'friday': 337,
 'getting': 338,
 'charges': 339,
 'really': 340,
 'dead': 341,
 'press': 342,
 'across': 343,
 'following': 344,
 'candidate': 345,
 'months': 346,
 'food': 347,
 'men': 348,
 'lot': 349,
 'parents': 350,
 'gun': 351,
 'money': 352,
 'don’t': 353,
 'love': 354,
 'working': 355,
 'come': 356,
 'leaders': 357,
 'cases': 358,
 'well': 359,
 'major': 360,
 'here': 361,
 'live': 362,
 'known': 363,
 'announced': 364,
 'cnn': 365,
 'film': 366,
 'climate': 367,
 'abortion': 368,
 'special': 369,
 'virus': 370,
 'saying': 371,
 'south': 372,
 'russia': 373,
 'stop': 374,
 'action': 375,
 'team': 376,
 'see': 377,
 'ever': 378,
 "didn't": 379,
 'border': 380,
 'several': 381,
 'movie': 382,
 'instagram': 383,
 "doesn't": 384,
 'child': 385,
 'daughter': 386,
 'nominee': 387,
 'mayor': 388,
 'judge': 389,
 'warned': 390,
 'others': 391,
 'again': 392,
 'kids': 393,
 'prime': 394,
 '2': 395,
 'lawmakers': 396,
 'little': 397,
 'trying': 398,
 'killing': 399,
 'chief': 400,
 'does': 401,
 'every': 402,
 'claimed': 403,
 'season': 404,
 '3': 405,
 'recent': 406,
 'event': 407,
 'same': 408,
 'then': 409,
 'call': 410,
 'protesters': 411,
 'tuesday': 412,
 'six': 413,
 'believe': 414,
 'committee': 415,
 'interview': 416,
 'water': 417,
 'service': 418,
 'information': 419,
 'led': 420,
 'united': 421,
 'move': 422,
 'trump’s': 423,
 'democrat': 424,
 'young': 425,
 'son': 426,
 'allegedly': 427,
 'conservative': 428,
 'rapper': 429,
 '5': 430,
 'minister': 431,
 'daily': 432,
 'calling': 433,
 'few': 434,
 'policy': 435,
 'ago': 436,
 'county': 437,
 'earlier': 438,
 'released': 439,
 'making': 440,
 'lives': 441,
 'america': 442,
 'officer': 443,
 'comedian': 444,
 'john': 445,
 'voters': 446,
 'once': 447,
 'already': 448,
 'comments': 449,
 'behind': 450,
 'past': 451,
 'jan': 452,
 'students': 453,
 'thing': 454,
 'place': 455,
 'control': 456,
 'tv': 457,
 'coming': 458,
 'hundreds': 459,
 'talk': 460,
 'early': 461,
 'open': 462,
 'defense': 463,
 'head': 464,
 'groups': 465,
 'sex': 466,
 'himself': 467,
 'yet': 468,
 'duchess': 469,
 'keep': 470,
 'wife': 471,
 'workers': 472,
 'likely': 473,
 'something': 474,
 'using': 475,
 'violence': 476,
 'd': 477,
 'legal': 478,
 'number': 479,
 'impeachment': 480,
 'seen': 481,
 'record': 482,
 'among': 483,
 'role': 484,
 "they're": 485,
 'ex': 486,
 'voting': 487,
 'showed': 488,
 'mass': 489,
 'run': 490,
 'enough': 491,
 'taken': 492,
 'won': 493,
 'crisis': 494,
 'give': 495,
 "there's": 496,
 'music': 497,
 'running': 498,
 'assault': 499,
 'previously': 500,
 'expected': 501,
 'game': 502,
 'vaccine': 503,
 'great': 504,
 'future': 505,
 'king': 506,
 'received': 507,
 'become': 508,
 'attacks': 509,
 'arrested': 510,
 'charged': 511,
 'order': 512,
 'local': 513,
 'duke': 514,
 'tweeted': 515,
 'near': 516,
 'fans': 517,
 'race': 518,
 'hours': 519,
 'lawyer': 520,
 'trial': 521,
 'officers': 522,
 'spread': 523,
 'community': 524,
 'real': 525,
 'wants': 526,
 'conspiracy': 527,
 'actress': 528,
 'tell': 529,
 'full': 530,
 'lady': 531,
 'robert': 532,
 'free': 533,
 'red': 534,
 "won't": 535,
 'wanted': 536,
 'ahead': 537,
 'share': 538,
 'gave': 539,
 'story': 540,
 'incident': 541,
 'win': 542,
 '18': 543,
 'lost': 544,
 'i’m': 545,
 '2016': 546,
 'plans': 547,
 'taking': 548,
 'forces': 549,
 'weekend': 550,
 'georgia': 551,
 "you're": 552,
 'plan': 553,
 'instead': 554,
 'stars': 555,
 'park': 556,
 'half': 557,
 'later': 558,
 'reports': 559,
 'air': 560,
 'despite': 561,
 'turned': 562,
 'james': 563,
 'online': 564,
 'such': 565,
 'calls': 566,
 'allegations': 567,
 'business': 568,
 'photo': 569,
 'netflix': 570,
 '“we': 571,
 'shared': 572,
 'victims': 573,
 'efforts': 574,
 "she's": 575,
 'district': 576,
 'agency': 577,
 'laws': 578,
 'mental': 579,
 'prison': 580,
 'fired': 581,
 'decades': 582,
 'mexico': 583,
 'force': 584,
 'wednesday': 585,
 'san': 586,
 'kim': 587,
 'lgbtq': 588,
 'claim': 589,
 'progressive': 590,
 'anchor': 591,
 'find': 592,
 'network': 593,
 'british': 594,
 'international': 595,
 'residents': 596,
 'union': 597,
 'appeared': 598,
 'almost': 599,
 'facebook': 600,
 'faces': 601,
 'question': 602,
 '4': 603,
 'meeting': 604,
 'things': 605,
 'looking': 606,
 'fight': 607,
 'emergency': 608,
 'bad': 609,
 '20': 610,
 'legislation': 611,
 'effort': 612,
 'center': 613,
 'thursday': 614,
 'activist': 615,
 'key': 616,
 'inside': 617,
 'pop': 618,
 'step': 619,
 'though': 620,
 'due': 621,
 'fbi': 622,
 'name': 623,
 'safety': 624,
 '2019': 625,
 'david': 626,
 'speaker': 627,
 'tonight': 628,
 'process': 629,
 'moment': 630,
 'mother': 631,
 'viral': 632,
 'virginia': 633,
 '7': 634,
 'pay': 635,
 'staff': 636,
 'held': 637,
 'ceremony': 638,
 'play': 639,
 'member': 640,
 '30': 641,
 'confirmed': 642,
 'potential': 643,
 'each': 644,
 'west': 645,
 'rock': 646,
 '50': 647,
 'suspect': 648,
 '100': 649,
 'dr': 650,
 'actually': 651,
 'lead': 652,
 'mike': 653,
 'global': 654,
 'intelligence': 655,
 '12': 656,
 'george': 657,
 'protests': 658,
 'different': 659,
 "can't": 660,
 'dozens': 661,
 'possible': 662,
 'job': 663,
 'leave': 664,
 'act': 665,
 'serious': 666,
 'university': 667,
 'jimmy': 668,
 'responded': 669,
 'husband': 670,
 'murder': 671,
 'list': 672,
 'lawmaker': 673,
 'congresswoman': 674,
 'hearing': 675,
 'mask': 676,
 'foreign': 677,
 '15': 678,
 'los': 679,
 'until': 680,
 'carolina': 681,
 'investigating': 682,
 'doing': 683,
 'program': 684,
 'together': 685,
 'based': 686,
 'biggest': 687,
 'might': 688,
 'outside': 689,
 'having': 690,
 'self': 691,
 'advice': 692,
 '“this': 693,
 'huffpost': 694,
 'movement': 695,
 'everyone': 696,
 'voted': 697,
 'speech': 698,
 'board': 699,
 'sussex': 700,
 'missing': 701,
 'building': 702,
 'church': 703,
 'families': 704,
 'multiple': 705,
 '11': 706,
 'lawsuit': 707,
 'related': 708,
 'adviser': 709,
 'ohio': 710,
 'matter': 711,
 'deaths': 712,
 'chris': 713,
 'criminal': 714,
 'comedy': 715,
 'thought': 716,
 'brought': 717,
 'father': 718,
 'victory': 719,
 'pro': 720,
 '2018': 721,
 'hospital': 722,
 '17': 723,
 'disease': 724,
 'angeles': 725,
 'storm': 726,
 'immigration': 727,
 'visit': 728,
 'popular': 729,
 'feel': 730,
 'organization': 731,
 'doesn’t': 732,
 '2017': 733,
 'r': 734,
 'ways': 735,
 'grand': 736,
 'point': 737,
 'southern': 738,
 'award': 739,
 'majority': 740,
 'arizona': 741,
 'try': 742,
 'living': 743,
 'positive': 744,
 'toward': 745,
 'tried': 746,
 'didn’t': 747,
 'civil': 748,
 'letter': 749,
 'racism': 750,
 'favorite': 751,
 'offered': 752,
 'facing': 753,
 'wall': 754,
 'let': 755,
 'spoke': 756,
 'clear': 757,
 'personal': 758,
 'test': 759,
 'critics': 760,
 'rally': 761,
 'nuclear': 762,
 'issues': 763,
 'winning': 764,
 'awards': 765,
 'results': 766,
 'finally': 767,
 'wing': 768,
 'powerful': 769,
 'jury': 770,
 'abuse': 771,
 'ban': 772,
 'line': 773,
 'term': 774,
 'executive': 775,
 'better': 776,
 'jr': 777,
 'injured': 778,
 'soon': 779,
 'issue': 780,
 'always': 781,
 'less': 782,
 'tweet': 783,
 'seven': 784,
 'expert': 785,
 'words': 786,
 'evidence': 787,
 'anyone': 788,
 'stage': 789,
 'china': 790,
 'mark': 791,
 'book': 792,
 'ukrainian': 793,
 'makes': 794,
 'ceo': 795,
 'prince': 796,
 'looks': 797,
 'supporters': 798,
 'release': 799,
 "that's": 800,
 'companies': 801,
 'protect': 802,
 'revealed': 803,
 'must': 804,
 'iran': 805,
 'opening': 806,
 'friends': 807,
 'hold': 808,
 'fun': 809,
 'playing': 810,
 'democracy': 811,
 'done': 812,
 'important': 813,
 'concerns': 814,
 'tested': 815,
 'chinese': 816,
 'elect': 817,
 'journalist': 818,
 'human': 819,
 'space': 820,
 'single': 821,
 'failed': 822,
 'medical': 823,
 'reality': 824,
 'age': 825,
 'threat': 826,
 'giant': 827,
 'described': 828,
 'problem': 829,
 'message': 830,
 'paid': 831,
 'became': 832,
 'giving': 833,
 'november': 834,
 'actions': 835,
 'cast': 836,
 'street': 837,
 'recently': 838,
 'opened': 839,
 'meet': 840,
 'bring': 841,
 'island': 842,
 'protest': 843,
 'emotional': 844,
 'criticism': 845,
 'am': 846,
 'masks': 847,
 '25': 848,
 'amazon': 849,
 'plus': 850,
 'system': 851,
 'can’t': 852,
 'wearing': 853,
 'large': 854,
 'johnson': 855,
 'obama': 856,
 'fall': 857,
 'follows': 858,
 'french': 859,
 "wasn't": 860,
 'crowd': 861,
 'countries': 862,
 'faced': 863,
 'began': 864,
 'data': 865,
 'teachers': 866,
 'posted': 867,
 'continue': 868,
 'oil': 869,
 'michigan': 870,
 'critical': 871,
 'access': 872,
 'debate': 873,
 'whose': 874,
 'appears': 875,
 'means': 876,
 'march': 877,
 'smith': 878,
 'users': 879,
 'statement': 880,
 'felt': 881,
 'primary': 882,
 'nothing': 883,
 'outbreak': 884,
 'tax': 885,
 'crime': 886,
 'counsel': 887,
 'growing': 888,
 'insurrection': 889,
 'watch': 890,
 'deadly': 891,
 'summer': 892,
 "state's": 893,
 'artist': 894,
 'final': 895,
 'highest': 896,
 'violent': 897,
 'morning': 898,
 'schools': 899,
 "isn't": 900,
 'crash': 901,
 'beyond': 902,
 'along': 903,
 'jersey': 904,
 'products': 905,
 "country's": 906,
 'billion': 907,
 'employees': 908,
 'urged': 909,
 'k': 910,
 'involved': 911,
 'author': 912,
 'helping': 913,
 'questions': 914,
 'activists': 915,
 'shootings': 916,
 'rule': 917,
 'millions': 918,
 'seeking': 919,
 'forced': 920,
 'c': 921,
 'racist': 922,
 'central': 923,
 'hurricane': 924,
 'miles': 925,
 'helped': 926,
 'everything': 927,
 'queen': 928,
 'ground': 929,
 'aid': 930,
 'nations': 931,
 'small': 932,
 'culture': 933,
 'refused': 934,
 'safe': 935,
 '8': 936,
 "biden's": 937,
 'nation': 938,
 'elections': 939,
 'upcoming': 940,
 'car': 941,
 'needs': 942,
 'risk': 943,
 'kevin': 944,
 '9': 945,
 'riot': 946,
 'probably': 947,
 'wrong': 948,
 'created': 949,
 "'": 950,
 "year's": 951,
 'appear': 952,
 'given': 953,
 'today': 954,
 'probe': 955,
 'account': 956,
 '“it': 957,
 'sent': 958,
 'israeli': 959,
 'met': 960,
 'elected': 961,
 'read': 962,
 'third': 963,
 'korean': 964,
 'hate': 965,
 'gets': 966,
 'european': 967,
 'caused': 968,
 'breaking': 969,
 'trip': 970,
 'saw': 971,
 'backed': 972,
 'veteran': 973,
 'elizabeth': 974,
 'battle': 975,
 'body': 976,
 'close': 977,
 'icon': 978,
 'attention': 979,
 'largest': 980,
 'super': 981,
 'hope': 982,
 'flight': 983,
 'hand': 984,
 'private': 985,
 'truth': 986,
 'hall': 987,
 'mind': 988,
 'summit': 989,
 'pennsylvania': 990,
 'quarterback': 991,
 'played': 992,
 'rules': 993,
 'treatment': 994,
 'apparently': 995,
 'continues': 996,
 'slammed': 997,
 'push': 998,
 'currently': 999,
 'sure': 1000,
 ...}

In [20]:
len(tokenizer.word_index)

19733

In [22]:
df=tokenizer.texts_to_sequences(df['short_description'])

In [23]:
df

[[125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29,
  9772,
  2,
  45,
  48,
  1221,
  8,
  2,
  857],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3,
  2,
  45,
  48,
  9774,
  270,
  7,
  679,
  725],
 [680, 41, 25, 4, 1023, 41, 249, 1769, 58, 85, 28, 9775],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678,
  14,
  4,
  681,
  9778,
  6841,
  7,
  9779,
  6842],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26,
  169,
  5,
  2,
  923,
  556,
  2424,
  281,
  632],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244,
  26,
  30,
  193,
  264,
  30,
  701,
  232,
  10],
 [1071,
  12,
  450,
  41,
  22,
  591,
  8,
  29,
  4509,
  9782,
  219,
  818,
  2222,
  3809,
  17,
  54,
  3355,
  53,
  22,
  416],
 [43,
  66,
  557,
  4,
  181,
  39,
  1877,
  245,
  417,
  418,
  159,
  179,
  26,
  2,
  726,
  4510,
  2,
  45,
  48,
  1878],
 [7,
  9783,
  327,
  9784,
  3810,
  9785,
  497,
  6843,
  14,
  2,
  1398,
  5,
  5389,
  6,
  4511,
  3,
  529,
  4,
  43,
  5390,
  727,
  540],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530,
  9787,
  6844,
  5,
  373,
  6,
  78,
  2679,
  309],
 [9788,
  19,
  356,
  220,
  1072,
  20,
  381,
  967,
  1166,
  9789,
  34,
  172,
  3,
  250,
  4,
  819,
  203,
  148,
  76,
  1662,
  16,
  2,
  140,
  2680],
 [2,
  541,
  3811,
  4,
  888,
  1222,
  5,
  658,
  76,
  2,
  1771,
  8,
  9790,
  9791,
  34,
  13,
  40,
  5,
  2,
  130,
  3356,
  357,
  7,
  9792,
  1879,
  1073],
 [924,
  9793,
  4510,
  2,
  6845,
  6,
  6846,
  3357,
  6,
  13,
  3812,
  3,
  9794,
  451,
  9795,
  558,
  36,
  110],
 [40,
  2681,
  334,
  12,
  21,
  6847,
  39,
  9,
  2,
  1025,
  968,
  381,
  729,
  9796,
  3,
  2425,
  4,
  9797,
  5391],
 [428,
  615,
  633,
  1566,
  2,
  471,
  5,
  310,
  133,
  214,
  4512,
  1566,
  19,
  1223,
  3,
  5392,
  7,
  4,
  6848,
  416,
  14,
  2,
  56,
  1772,
  682,
  2,
  452,
  282,
  889],
 [9798,
  482,
  969,
  970,
  3,
  5393,
  820,
  971,
  104,
  2987,
  2223,
  634,
  9799,
  311,
  6,
  1074,
  293,
  9800,
  181,
  925],
 [1475,
  9801,
  331,
  616,
  5394,
  6849,
  6,
  5395,
  9802,
  2,
  3813,
  68,
  858,
  2,
  3358,
  5,
  4,
  5396,
  461,
  5397,
  2988],
 [9803,
  9804,
  34,
  926,
  2,
  679,
  725,
  4513,
  542,
  159,
  140,
  287,
  3814,
  14,
  15,
  3815,
  6850,
  6851,
  19,
  187],
 [2,
  9805,
  6,
  9806,
  2040,
  972,
  574,
  3,
  6852,
  53,
  312,
  5398,
  85,
  251,
  2,
  789,
  8,
  2224,
  3,
  6853,
  2,
  309],
 [2,
  6845,
  6,
  6846,
  3357,
  173,
  2225,
  4,
  6854,
  17,
  2,
  5399,
  726,
  1224,
  2989,
  9807,
  1399,
  55,
  2,
  6855,
  3359,
  6,
  3360,
  5400],
 [8,
  2,
  451,
  543,
  346,
  1225,
  19,
  4514,
  9808,
  2,
  4515,
  26,
  559,
  12,
  2,
  9809,
  6856,
  335,
  5,
  1476,
  157,
  1880,
  1477,
  75,
  121,
  335],
 [18, 763, 6857, 17, 2426, 14, 790, 1026],
 [2,
  726,
  2226,
  50,
  2,
  294,
  3361,
  6,
  6858,
  3362,
  6,
  6859,
  7,
  3360,
  5400,
  209,
  2,
  295,
  10,
  2,
  1226,
  13,
  9810,
  31],
 [2,
  821,
  3816,
  1075,
  13,
  5401,
  7,
  2,
  168,
  4516,
  560,
  2427,
  9,
  177,
  63,
  23,
  2428,
  60,
  4,
  1400,
  399,
  2,
  1773,
  123,
  10],
 [22, 1478, 3363, 204, 9, 4, 659, 730, 17, 1227, 1167, 6860, 60, 99, 9811],
 [791, 9812, 4, 1881, 973, 6, 2990, 4517, 13, 4518, 7, 2227, 7, 1479, 225],
 [1882, 1883, 300, 57, 4, 2682, 1076, 1663, 100, 680, 177],
 [18,
  155,
  114,
  6,
  61,
  531,
  3364,
  114,
  49,
  483,
  319,
  5,
  9813,
  100,
  20,
  9814,
  6,
  2991,
  3,
  9815,
  6,
  140,
  357,
  100,
  3,
  635,
  42,
  6861],
 [2,
  9816,
  327,
  10,
  6862,
  5,
  15,
  5402,
  382,
  24,
  160,
  5403,
  14,
  927,
  1115,
  50,
  136,
  134,
  179],
 [9817,
  532,
  363,
  17,
  2,
  859,
  3817,
  126,
  19,
  6863,
  2,
  9818,
  9819,
  6,
  2,
  3365,
  67,
  702],
 [45,
  48,
  18,
  155,
  114,
  7,
  1401,
  8,
  2,
  1771,
  5,
  928,
  974,
  2041,
  105,
  15,
  1077,
  281,
  50,
  3,
  2,
  1078,
  193,
  2683,
  2,
  9820,
  180,
  301,
  4,
  9821,
  4519,
  31],
 [561,
  2228,
  1027,
  419,
  42,
  202,
  860,
  9822,
  1664,
  6,
  7,
  69,
  358,
  2,
  2684,
  9823,
  507,
  5404,
  2,
  270,
  5,
  3818,
  252,
  264],
 [9, 244, 2, 3819, 61, 164, 5405, 5, 2685, 1306, 3820, 6864, 6, 4520, 5406],
 [2, 92, 44, 82, 194, 2038, 60, 2, 9824, 7, 4, 822, 2042, 3, 2229, 77],
 [3821,
  296,
  111,
  39,
  35,
  28,
  6865,
  3,
  2,
  2043,
  1307,
  726,
  17,
  4,
  9825,
  726,
  31],
 [3360,
  5400,
  13,
  220,
  4,
  924,
  890,
  320,
  17,
  2,
  726,
  6866,
  2992,
  2,
  45,
  48,
  1878],
 [2,
  140,
  125,
  731,
  11,
  2044,
  2,
  4521,
  32,
  4,
  9826,
  9827,
  7,
  2,
  1567,
  5,
  2,
  891,
  3362,
  7,
  6867,
  36,
  892,
  17,
  2045,
  6,
  823,
  472,
  9,
  2,
  929,
  518,
  3,
  975,
  2429,
  5,
  9828,
  6,
  101,
  5407],
 [4522,
  25,
  1079,
  3366,
  12,
  2046,
  164,
  188,
  5,
  417,
  3367,
  732,
  202,
  100,
  37,
  1115,
  95,
  9,
  2,
  2430,
  7,
  1402],
 [6868,
  7,
  2,
  302,
  5,
  2,
  9829,
  3368,
  270,
  19,
  4,
  4523,
  5,
  6869,
  420,
  258,
  3,
  9830,
  2047,
  31,
  2431,
  331,
  1774,
  93,
  2,
  178],
 [2,
  327,
  5,
  2,
  1228,
  6870,
  366,
  1775,
  4,
  1403,
  5,
  2,
  733,
  3369,
  8,
  2,
  3370,
  5408,
  7,
  2,
  3822,
  3823,
  3371],
 [107,
  2686,
  55,
  2,
  5409,
  45,
  48,
  3372,
  20,
  2227,
  3373,
  4524,
  250,
  8,
  9831,
  2230],
 [3374,
  2231,
  4525,
  544,
  22,
  1665,
  6,
  19,
  6871,
  5,
  3375,
  617,
  30,
  976,
  20,
  4,
  4526,
  4527,
  4528,
  3824,
  12,
  149,
  30,
  1776,
  6,
  159,
  101,
  121,
  1080,
  617,
  22,
  1480,
  703,
  5410,
  111,
  436],
 [4,
  6872,
  417,
  6873,
  19,
  47,
  3825,
  8,
  6874,
  1081,
  6,
  2,
  67,
  35,
  374,
  6875,
  50,
  533,
  5411,
  417,
  9,
  320],
 [221,
  9832,
  5,
  2,
  9833,
  100,
  9834,
  2048,
  498,
  68,
  100,
  11,
  1308,
  3,
  977,
  7,
  1777,
  6876,
  4,
  1229,
  5,
  288,
  115,
  9835,
  7,
  3376,
  3826,
  7,
  29,
  142],
 [2,
  46,
  88,
  56,
  400,
  5,
  636,
  19,
  562,
  55,
  1568,
  17,
  259,
  5,
  4,
  158,
  235,
  60,
  2,
  452,
  282,
  1028,
  499,
  9,
  2,
  303],
 [2,
  9836,
  157,
  6877,
  29,
  792,
  9837,
  13,
  1569,
  5412,
  311,
  100,
  680,
  54,
  281,
  2432,
  3,
  30,
  2433,
  8,
  250],
 [9838,
  2434,
  4529,
  3,
  2,
  3377,
  930,
  6,
  637,
  152,
  30,
  9839,
  680,
  77,
  2435,
  5413,
  36,
  860,
  2,
  61,
  84,
  2434,
  127,
  25,
  2436,
  4,
  182],
 [2,
  1029,
  1168,
  10,
  54,
  1116,
  50,
  8,
  313,
  519,
  4,
  99,
  8,
  30,
  484,
  7,
  2,
  29,
  375,
  382],
 [2,
  824,
  86,
  93,
  563,
  2049,
  575,
  9840,
  50,
  199,
  1884,
  102,
  38,
  355,
  4530,
  545,
  683],
 [2,
  1882,
  1883,
  9841,
  24,
  1885,
  3,
  592,
  50,
  34,
  215,
  2,
  5414,
  978,
  2437,
  111,
  436],
 [2,
  1666,
  764,
  429,
  2687,
  86,
  1082,
  205,
  16,
  2,
  2050,
  9842,
  174,
  7,
  2993,
  3378,
  3,
  141,
  2,
  1404],
 [6878,
  2,
  46,
  45,
  48,
  1570,
  3,
  2,
  421,
  931,
  6,
  4,
  6879,
  9843,
  7,
  3379,
  1571,
  637,
  5415,
  14,
  276,
  357],
 [2, 2438, 765, 638, 544, 2994, 260, 430, 181, 1230, 1405, 3, 78, 1028, 684],
 [88,
  56,
  342,
  226,
  6880,
  2688,
  5416,
  10,
  4,
  4531,
  1231,
  11,
  38,
  5417,
  6,
  81,
  1886,
  704,
  17,
  359,
  17,
  1481],
 [2,
  893,
  252,
  6881,
  11,
  2689,
  3,
  185,
  46,
  9844,
  388,
  9845,
  9846,
  734,
  7,
  2,
  252,
  135],
 [4,
  45,
  48,
  1770,
  12,
  9847,
  1027,
  564,
  334,
  559,
  12,
  6882,
  8,
  419,
  32,
  1887,
  108,
  6883,
  9,
  2051,
  24,
  473,
  3,
  1169,
  53,
  766,
  6884,
  14,
  1667],
 [9, 4, 2995, 2690, 1482, 1483, 4532, 260, 26, 4, 5418, 2691, 7, 1083],
 [2, 327, 13, 304, 363, 8, 2, 5419, 382, 9848],
 [485,
  4533,
  8,
  5420,
  4534,
  52,
  91,
  35,
  170,
  2439,
  3827,
  227,
  33,
  9849,
  9850,
  6885,
  12,
  25,
  6886,
  7,
  2,
  115],
 [1309,
  401,
  38,
  5421,
  534,
  6,
  1232,
  2,
  18,
  10,
  244,
  2692,
  1309,
  11,
  474,
  70,
  94,
  122,
  685],
 [34,
  70,
  25,
  9,
  2,
  1400,
  11,
  34,
  1233,
  2232,
  639,
  31,
  1084,
  93,
  153,
  108,
  177],
 [2,
  9851,
  2052,
  91,
  6887,
  2693,
  535,
  25,
  3,
  3828,
  14,
  2,
  4535,
  72,
  1778,
  6888,
  6,
  1779,
  6889,
  311,
  3,
  3380,
  42,
  1572],
 [9852, 9853, 2233, 14, 2, 2053, 9854, 6, 1030, 15, 175, 1031, 1234, 7, 546],
 [213,
  7,
  2,
  1780,
  43,
  2996,
  56,
  576,
  24,
  6890,
  34,
  35,
  191,
  9,
  4,
  729,
  107,
  46,
  388],
 [114,
  547,
  3,
  4536,
  979,
  3,
  4,
  29,
  9855,
  972,
  1310,
  12,
  3829,
  3,
  5422,
  475,
  1668,
  3381,
  3,
  1484,
  76,
  705,
  9856],
 [2,
  1485,
  686,
  894,
  19,
  171,
  5423,
  735,
  3,
  2997,
  2998,
  32,
  1117,
  6891,
  6892,
  6,
  2234,
  7,
  30,
  3830],
 [289,
  38,
  32,
  9857,
  72,
  131,
  9858,
  2,
  5424,
  5,
  6893,
  9859,
  1888,
  2,
  29,
  1311,
  2999,
  15,
  5425,
  100,
  402,
  9860,
  5,
  23],
 [4537,
  9861,
  3382,
  9862,
  9863,
  7,
  2,
  45,
  48,
  462,
  895,
  3,
  9864,
  15,
  61,
  736,
  1889,
  16,
  825,
  92,
  6,
  508,
  2,
  3383,
  126,
  3,
  422,
  53,
  3,
  75,
  260,
  7,
  2,
  3831],
 [3000,
  113,
  3001,
  76,
  4,
  1669,
  1486,
  210,
  3832,
  12,
  13,
  160,
  888,
  6,
  1118,
  319,
  5,
  4538,
  1312],
 [18,
  155,
  114,
  19,
  2694,
  2,
  5426,
  1573,
  5,
  2,
  3384,
  706,
  509,
  548,
  259,
  7,
  4,
  9865,
  9866,
  5427,
  638,
  637,
  16,
  2,
  3833,
  220,
  4,
  6894,
  1399],
 [2043,
  6895,
  1235,
  4,
  737,
  8,
  9867,
  9,
  2,
  3834,
  509,
  9868,
  168,
  285,
  9869,
  4524,
  4,
  45,
  48,
  9870,
  9,
  9871,
  3835],
 [2,
  2235,
  40,
  5,
  2,
  296,
  687,
  3836,
  294,
  6896,
  7,
  2,
  140,
  19,
  47,
  5428,
  33,
  276,
  549,
  138,
  461,
  7,
  2,
  309,
  97,
  2694,
  78,
  9872,
  99,
  9,
  177],
 [9873,
  6897,
  11,
  2054,
  17,
  2,
  980,
  2440,
  593,
  6,
  35,
  473,
  1670,
  1072,
  8,
  6898,
  6,
  157,
  3837,
  3,
  6899,
  2,
  3002,
  17,
  359],
 [2,
  214,
  328,
  1406,
  59,
  1671,
  2695,
  8,
  2,
  484,
  423,
  376,
  1406,
  4,
  1671,
  389,
  6,
  4,
  520],
 [2,
  327,
  93,
  2,
  1574,
  21,
  13,
  981,
  3838,
  3,
  28,
  767,
  9874,
  53,
  382,
  59,
  100,
  17,
  21,
  19,
  159,
  2696,
  9875,
  7,
  2,
  1890],
 [1575,
  463,
  1891,
  364,
  12,
  1032,
  35,
  28,
  1487,
  109,
  7,
  59,
  1033,
  209,
  4,
  793,
  3839,
  1672,
  19,
  113,
  2054,
  5429],
 [26,
  4,
  296,
  99,
  1236,
  1222,
  12,
  293,
  3840,
  2,
  4539,
  3361,
  738,
  210,
  192,
  4540,
  1085,
  37,
  71,
  4,
  6900,
  2697,
  726],
 [793, 549, 24, 2441, 29, 3841, 7, 42, 9876, 76, 276, 549, 7, 2, 3003],
 [6901,
  1237,
  176,
  7,
  4,
  2698,
  5,
  6902,
  8,
  1576,
  111,
  5,
  418,
  31,
  2,
  618,
  86,
  93,
  2,
  861,
  26,
  21,
  6903,
  15,
  9877,
  4541,
  2442,
  1119],
 [9878, 9879, 1407, 85, 28, 4, 360, 2236, 3, 2, 734, 1238, 1577, 982, 5, 5430],
 [305, 594, 6, 595, 3385, 1578, 2, 4542, 5, 2, 45, 9880, 48, 2048, 6904, 3842],
 [2,
  92,
  44,
  82,
  189,
  5431,
  6,
  1892,
  978,
  35,
  1579,
  2,
  1307,
  9881,
  739,
  8,
  30,
  1673,
  9,
  283,
  4543,
  574],
 [1408,
  20,
  6905,
  3386,
  3387,
  10,
  862,
  6906,
  43,
  1239,
  8,
  367,
  236,
  183,
  25,
  863,
  36,
  1488],
 [2055,
  437,
  164,
  5432,
  532,
  9882,
  13,
  510,
  7,
  2,
  1781,
  3388,
  5,
  1580,
  1674,
  34,
  57,
  47,
  682,
  15,
  270],
 [2, 1675, 6907, 7, 2237, 55, 2, 46, 61, 3843, 9883, 1034, 8, 2, 9884, 99],
 [2,
  106,
  10,
  21,
  13,
  103,
  5433,
  9885,
  117,
  278,
  2,
  287,
  5434,
  12,
  21,
  6908,
  8,
  15,
  182,
  6,
  13,
  1240,
  1409,
  2,
  3389,
  117,
  3844],
 [1893,
  5,
  2,
  1676,
  403,
  9886,
  113,
  2,
  6889,
  9887,
  9888,
  37,
  2,
  893,
  896,
  133,
  1569,
  12,
  3004],
 [2,
  707,
  105,
  1581,
  2238,
  3390,
  9889,
  3,
  1241,
  163,
  6909,
  794,
  23,
  1582,
  8,
  39,
  475,
  9890,
  9891,
  72,
  9892,
  3,
  314,
  145],
 [2,
  253,
  7,
  9893,
  22,
  163,
  864,
  112,
  412,
  6,
  2056,
  305,
  472,
  6,
  3391,
  617,
  2,
  4544,
  540,
  4545],
 [2,
  3845,
  1120,
  1410,
  35,
  767,
  28,
  4,
  640,
  5,
  2,
  6910,
  6911,
  9894,
  14,
  4546,
  101,
  3392,
  343,
  5435],
 [7,
  130,
  5,
  2,
  1313,
  6912,
  290,
  12,
  2057,
  6913,
  1121,
  2699,
  49,
  6914,
  897,
  9895,
  72,
  9896,
  100,
  83,
  52,
  9897,
  16,
  64],
 [228,
  24,
  2443,
  109,
  6,
  306,
  11,
  3393,
  3,
  619,
  7,
  131,
  26,
  2,
  115,
  2700,
  2,
  2444,
  9898,
  9899],
 [1086,
  123,
  7,
  3005,
  261,
  91,
  22,
  461,
  898,
  294,
  6915,
  11,
  1894,
  983,
  3394,
  131,
  17,
  3395,
  19,
  47,
  6916],
 [2,
  464,
  5,
  2,
  595,
  3836,
  1489,
  577,
  390,
  2,
  45,
  1024,
  285,
  1242,
  12,
  9900,
  336,
  336,
  6917,
  85,
  191,
  6918,
  16,
  9901],
 [565,
  509,
  25,
  508,
  4,
  888,
  826,
  3,
  45,
  48,
  899,
  14,
  381,
  284,
  2445,
  4547,
  264,
  138,
  73,
  44],
 [4, 271, 253, 149, 59, 39, 7, 1486, 210, 36, 550],
 [2,
  3846,
  9902,
  9903,
  6919,
  1895,
  192,
  4548,
  60,
  1243,
  3847,
  1782,
  7,
  4,
  296,
  4532,
  1490,
  3,
  2,
  6920],
 [2, 163, 1235, 220, 4, 6872, 417, 2446, 97, 61, 281, 60, 1244, 9, 1083, 641],
 [2,
  197,
  178,
  827,
  13,
  5436,
  8,
  2239,
  5,
  865,
  2701,
  578,
  708,
  3,
  419,
  32,
  205,
  9,
  383],
 [136,
  11,
  29,
  284,
  9904,
  216,
  2,
  261,
  6921,
  164,
  899,
  12,
  160,
  900,
  3355,
  6,
  4,
  1245,
  77,
  3006,
  12,
  165,
  704,
  249,
  3007],
 [2,
  1896,
  265,
  26,
  2,
  114,
  188,
  642,
  12,
  2,
  276,
  297,
  7,
  1897,
  204,
  1783,
  5,
  1170,
  5437,
  5438,
  8,
  314,
  7,
  291],
 [2, 17, 23, 13, 189, 10, 21, 71, 732, 377, 165, 6922, 237, 497, 6, 1314],
 [9905,
  9906,
  10,
  1667,
  9907,
  2,
  643,
  8,
  2696,
  1315,
  1316,
  6,
  131,
  476,
  9,
  135,
  99],
 [9908, 795, 4549, 796, 57, 500, 3396, 566, 3, 1241, 2, 1317],
 [329,
  2058,
  7,
  119,
  9909,
  17,
  195,
  17,
  21,
  384,
  1677,
  176,
  72,
  119,
  193,
  2,
  4550,
  3008],
 [63,
  6923,
  9910,
  797,
  16,
  2,
  6924,
  12,
  3397,
  152,
  30,
  9911,
  54,
  660,
  170,
  1583,
  127,
  1171,
  63,
  4,
  1898,
  4551,
  30,
  1411,
  3848,
  768,
  16,
  3398,
  2447,
  7,
  2702,
  261,
  399,
  92,
  205,
  6,
  59,
  866,
  6,
  1087,
  30,
  6,
  391,
  1318],
 [2703,
  9912,
  566,
  9,
  798,
  3,
  217,
  26,
  178,
  344,
  3399,
  3400,
  5439,
  540,
  2448,
  9913,
  1584,
  3,
  283,
  368,
  465],
 [77,
  7,
  1899,
  91,
  22,
  1491,
  19,
  47,
  113,
  7,
  2,
  6925,
  5,
  4,
  242,
  34,
  13,
  3849,
  117,
  6926],
 [596,
  5,
  6874,
  740,
  121,
  1081,
  160,
  249,
  25,
  1900,
  417,
  26,
  2240,
  6886,
  2,
  2704,
  2449],
 [232,
  2450,
  12,
  43,
  1678,
  11,
  501,
  17,
  3401,
  9914,
  9915,
  20,
  1901,
  5440,
  2240,
  12,
  25,
  149,
  293,
  260,
  1902,
  39],
 [453,
  34,
  1903,
  2,
  127,
  1171,
  278,
  16,
  3398,
  2447,
  7,
  261,
  24,
  1679,
  2,
  892,
  14,
  4,
  65,
  5,
  579,
  125,
  763,
  211,
  6927],
 [5441,
  6,
  1245,
  1399,
  9916,
  1492,
  5,
  9917,
  551,
  9,
  177,
  3850,
  4552,
  1678,
  6,
  6928,
  284,
  5442,
  7,
  69,
  1904],
 [5443,
  688,
  1583,
  2,
  4553,
  3402,
  824,
  287,
  20,
  2,
  461,
  5397,
  2,
  3851,
  287,
  35,
  28,
  3403,
  16,
  2,
  3404,
  9918,
  9919,
  3009,
  7,
  1319],
 [4,
  1773,
  19,
  47,
  510,
  26,
  9920,
  4,
  932,
  5444,
  55,
  6929,
  1402,
  117,
  1118,
  3,
  901,
  60,
  4,
  3010,
  1565],
 [259, 5, 2, 820, 3011, 5445, 684, 2, 3012, 11, 2, 130, 769, 3, 1680],
 [4554, 1035, 2705, 9921, 3852, 33, 1905, 661, 10, 123],
 [9922,
  77,
  511,
  9923,
  9924,
  9925,
  14,
  159,
  9926,
  1585,
  5,
  3405,
  5,
  2701,
  21,
  85,
  185,
  53,
  3,
  40,
  44,
  7,
  1681,
  8,
  644,
  1122],
 [9927,
  46,
  1412,
  2451,
  9928,
  11,
  71,
  194,
  1308,
  3,
  1123,
  1407,
  3,
  2,
  736,
  770,
  9,
  337],
 [2,
  726,
  100,
  2,
  61,
  924,
  5,
  22,
  4555,
  2706,
  726,
  404,
  100,
  11,
  9929,
  32,
  9930,
  925,
  645,
  5,
  2,
  9931],
 [2,
  1088,
  616,
  1771,
  2241,
  2,
  9932,
  9933,
  32,
  2,
  5446,
  5,
  9934,
  34,
  11,
  9935,
  33,
  165,
  16,
  139,
  8,
  2,
  3013,
  5,
  2,
  3014,
  597],
 [2,
  4556,
  983,
  5,
  2,
  9936,
  1493,
  5445,
  51,
  3012,
  100,
  2,
  130,
  769,
  378,
  3406,
  33,
  6930,
  100,
  13,
  3407,
  112,
  7,
  2,
  9937,
  244],
 [2,
  2444,
  1682,
  1483,
  3,
  405,
  634,
  20,
  4,
  557,
  2059,
  1088,
  5,
  405,
  430,
  7,
  1083,
  17,
  43,
  272,
  332,
  129,
  2,
  6931,
  3,
  218,
  8,
  1320],
 [9938,
  9939,
  57,
  1784,
  3,
  1906,
  1785,
  1907,
  6,
  5447,
  9940,
  3002,
  97,
  9941,
  22,
  5448,
  385,
  17,
  22,
  3015,
  63,
  54,
  13,
  61,
  1908,
  8,
  475,
  2,
  3853],
 [83,
  79,
  6932,
  11,
  9942,
  72,
  552,
  3408,
  5,
  1909,
  216,
  1786,
  9943,
  6,
  5449,
  5,
  9944,
  3016,
  36,
  2707,
  85,
  28,
  8,
  41],
 [2,
  6933,
  13,
  637,
  33,
  6934,
  8,
  293,
  313,
  346,
  344,
  22,
  1321,
  2242,
  5,
  30,
  6935,
  6936,
  139],
 [2, 9945, 290, 4, 6937, 126, 1240, 4, 2243],
 [2,
  1901,
  534,
  5450,
  11,
  3017,
  4,
  5451,
  6938,
  12,
  127,
  116,
  1124,
  62,
  2,
  9946,
  1236,
  1222],
 [2,
  9947,
  51,
  1494,
  41,
  3854,
  894,
  2241,
  9,
  1125,
  76,
  4,
  933,
  209,
  1117,
  189,
  9948,
  49,
  501,
  3,
  3018,
  4,
  1246,
  9949,
  3,
  141,
  23,
  266],
 [2,
  2244,
  2060,
  2061,
  828,
  80,
  27,
  6,
  15,
  3409,
  198,
  38,
  984,
  55,
  3410,
  6939,
  16,
  2,
  1495],
 [2,
  3014,
  9950,
  73,
  208,
  194,
  2452,
  293,
  260,
  181,
  131,
  620,
  21,
  934,
  3,
  2708,
  2,
  3019,
  9,
  1910],
 [2,
  147,
  11,
  2453,
  3,
  9951,
  1683,
  7,
  463,
  5,
  89,
  27,
  561,
  29,
  419,
  9952,
  3,
  3410,
  1089,
  637,
  16,
  15,
  333,
  3009],
 [134,
  24,
  2,
  687,
  6940,
  7,
  2,
  140,
  1496,
  6941,
  10,
  7,
  323,
  3,
  2,
  486,
  18,
  1911,
  246,
  1126,
  1089,
  16,
  15,
  985,
  3411],
 [1247,
  5452,
  42,
  277,
  76,
  2,
  189,
  34,
  3020,
  167,
  5,
  5453,
  385,
  321,
  771,
  2454,
  7,
  15,
  238,
  521],
 [102, 40, 454, 26, 315, 8, 89, 98, 829, 5454, 986, 197],
 [902,
  9953,
  136,
  24,
  101,
  1684,
  534,
  3412,
  12,
  552,
  1685,
  14,
  5455,
  2678,
  6942],
 [2455,
  239,
  3,
  639,
  64,
  1172,
  9954,
  361,
  31,
  2,
  5445,
  2062,
  2709,
  10,
  26,
  2,
  61,
  2456,
  13,
  9955],
 [9956,
  34,
  16,
  40,
  737,
  1322,
  17,
  4,
  88,
  56,
  222,
  709,
  11,
  10,
  3,
  25,
  4557,
  27,
  9957,
  16,
  4,
  1126,
  418,
  2063,
  62,
  2,
  303,
  162],
 [1686,
  35,
  799,
  4,
  413,
  259,
  1173,
  53,
  3,
  2,
  287,
  4558,
  7,
  2457,
  32,
  2,
  3855,
  466,
  4559,
  420,
  33,
  3856,
  9958],
 [3857,
  14,
  9959,
  3016,
  9960,
  9961,
  477,
  9962,
  730,
  22,
  2710,
  37,
  3413,
  1222,
  5,
  3414,
  1413,
  72,
  101,
  2064,
  6943,
  118,
  9963,
  6,
  102,
  43,
  1684,
  66,
  41,
  688,
  273],
 [2,
  2051,
  3415,
  1090,
  9964,
  9965,
  6,
  2,
  9966,
  429,
  113,
  42,
  3021,
  164,
  100,
  37,
  30,
  486,
  9967,
  3022,
  11,
  38,
  1248,
  32,
  23],
 [56,
  335,

In [24]:
input_sequences = []
for seq in df:
    if len(seq)<2:
        continue
    for i in range(1, len(seq)):
        ngram = seq[:i+1]
        input_sequences.append(ngram)

In [25]:
input_sequences

[[125, 257],
 [125, 257, 10],
 [125, 257, 10, 23],
 [125, 257, 10, 23, 11],
 [125, 257, 10, 23, 11, 241],
 [125, 257, 10, 23, 11, 241, 461],
 [125, 257, 10, 23, 11, 241, 461, 3],
 [125, 257, 10, 23, 11, 241, 461, 3, 3805],
 [125, 257, 10, 23, 11, 241, 461, 3, 3805, 322],
 [125, 257, 10, 23, 11, 241, 461, 3, 3805, 322, 1305],
 [125, 257, 10, 23, 11, 241, 461, 3, 3805, 322, 1305, 81],
 [125, 257, 10, 23, 11, 241, 461, 3, 3805, 322, 1305, 81, 1768],
 [125, 257, 10, 23, 11, 241, 461, 3, 3805, 322, 1305, 81, 1768, 53],
 [125, 257, 10, 23, 11, 241, 461, 3, 3805, 322, 1305, 81, 1768, 53, 14],
 [125, 257, 10, 23, 11, 241, 461, 3, 3805, 322, 1305, 81, 1768, 53, 14, 2],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29,
  9772],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29,
  9772,
  2],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29,
  9772,
  2,
  45],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29,
  9772,
  2,
  45,
  48],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29,
  9772,
  2,
  45,
  48,
  1221],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29,
  9772,
  2,
  45,
  48,
  1221,
  8],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29,
  9772,
  2,
  45,
  48,
  1221,
  8,
  2],
 [125,
  257,
  10,
  23,
  11,
  241,
  461,
  3,
  3805,
  322,
  1305,
  81,
  1768,
  53,
  14,
  2,
  9771,
  181,
  2677,
  5,
  2,
  29,
  9772,
  2,
  45,
  48,
  1221,
  8,
  2,
  857],
 [21, 13],
 [21, 13, 9773],
 [21, 13, 9773, 33],
 [21, 13, 9773, 33, 2037],
 [21, 13, 9773, 33, 2037, 6],
 [21, 13, 9773, 33, 2037, 6, 1661],
 [21, 13, 9773, 33, 2037, 6, 1661, 63],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21, 2038],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21, 2038, 3],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21, 2038, 3, 2],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21, 2038, 3, 2, 109],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21, 2038, 3, 2, 109, 5],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21, 2038, 3, 2, 109, 5, 2],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21, 2038, 3, 2, 109, 5, 2, 2039],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21, 2038, 3, 2, 109, 5, 2, 2039, 26],
 [21, 13, 9773, 33, 2037, 6, 1661, 63, 21, 2038, 3, 2, 109, 5, 2, 2039, 26, 2],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3,
  2],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3,
  2,
  45],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3,
  2,
  45,
  48],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3,
  2,
  45,
  48,
  9774],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3,
  2,
  45,
  48,
  9774,
  270],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3,
  2,
  45,
  48,
  9774,
  270,
  7],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3,
  2,
  45,
  48,
  9774,
  270,
  7,
  679],
 [21,
  13,
  9773,
  33,
  2037,
  6,
  1661,
  63,
  21,
  2038,
  3,
  2,
  109,
  5,
  2,
  2039,
  26,
  2,
  4507,
  190,
  3,
  2,
  45,
  48,
  9774,
  270,
  7,
  679,
  725],
 [680, 41],
 [680, 41, 25],
 [680, 41, 25, 4],
 [680, 41, 25, 4, 1023],
 [680, 41, 25, 4, 1023, 41],
 [680, 41, 25, 4, 1023, 41, 249],
 [680, 41, 25, 4, 1023, 41, 249, 1769],
 [680, 41, 25, 4, 1023, 41, 249, 1769, 58],
 [680, 41, 25, 4, 1023, 41, 249, 1769, 58, 85],
 [680, 41, 25, 4, 1023, 41, 249, 1769, 58, 85, 28],
 [680, 41, 25, 4, 1023, 41, 249, 1769, 58, 85, 28, 9775],
 [3806, 263],
 [3806, 263, 3807],
 [3806, 263, 3807, 53],
 [3806, 263, 3807, 53, 6839],
 [3806, 263, 3807, 53, 6839, 9],
 [3806, 263, 3807, 53, 6839, 9, 119],
 [3806, 263, 3807, 53, 6839, 9, 119, 9776],
 [3806, 263, 3807, 53, 6839, 9, 119, 9776, 9777],
 [3806, 263, 3807, 53, 6839, 9, 119, 9776, 9777, 6],
 [3806, 263, 3807, 53, 6839, 9, 119, 9776, 9777, 6, 21],
 [3806, 263, 3807, 53, 6839, 9, 119, 9776, 9777, 6, 21, 6840],
 [3806, 263, 3807, 53, 6839, 9, 119, 9776, 9777, 6, 21, 6840, 96],
 [3806, 263, 3807, 53, 6839, 9, 119, 9776, 9777, 6, 21, 6840, 96, 51],
 [3806, 263, 3807, 53, 6839, 9, 119, 9776, 9777, 6, 21, 6840, 96, 51, 13],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678,
  14],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678,
  14,
  4],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678,
  14,
  4,
  681],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678,
  14,
  4,
  681,
  9778],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678,
  14,
  4,
  681,
  9778,
  6841],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678,
  14,
  4,
  681,
  9778,
  6841,
  7],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678,
  14,
  4,
  681,
  9778,
  6841,
  7,
  9779],
 [3806,
  263,
  3807,
  53,
  6839,
  9,
  119,
  9776,
  9777,
  6,
  21,
  6840,
  96,
  51,
  13,
  2985,
  15,
  2678,
  14,
  4,
  681,
  9778,
  6841,
  7,
  9779,
  6842],
 [1474, 2423],
 [1474, 2423, 167],
 [1474, 2423, 167, 3354],
 [1474, 2423, 167, 3354, 1770],
 [1474, 2423, 167, 3354, 1770, 4508],
 [1474, 2423, 167, 3354, 1770, 4508, 9780],
 [1474, 2423, 167, 3354, 1770, 4508, 9780, 5],
 [1474, 2423, 167, 3354, 1770, 4508, 9780, 5, 5388],
 [1474, 2423, 167, 3354, 1770, 4508, 9780, 5, 5388, 3808],
 [1474, 2423, 167, 3354, 1770, 4508, 9780, 5, 5388, 3808, 30],
 [1474, 2423, 167, 3354, 1770, 4508, 9780, 5, 5388, 3808, 30, 6],
 [1474, 2423, 167, 3354, 1770, 4508, 9780, 5, 5388, 3808, 30, 6, 9781],
 [1474, 2423, 167, 3354, 1770, 4508, 9780, 5, 5388, 3808, 30, 6, 9781, 30],
 [1474, 2423, 167, 3354, 1770, 4508, 9780, 5, 5388, 3808, 30, 6, 9781, 30, 4],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26,
  169],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26,
  169,
  5],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26,
  169,
  5,
  2],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26,
  169,
  5,
  2,
  923],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26,
  169,
  5,
  2,
  923,
  556],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26,
  169,
  5,
  2,
  923,
  556,
  2424],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26,
  169,
  5,
  2,
  923,
  556,
  2424,
  281],
 [1474,
  2423,
  167,
  3354,
  1770,
  4508,
  9780,
  5,
  5388,
  3808,
  30,
  6,
  9781,
  30,
  4,
  922,
  26,
  169,
  5,
  2,
  923,
  556,
  2424,
  281,
  632],
 [2, 2986],
 [2, 2986, 44],
 [2, 2986, 44, 82],
 [2, 2986, 44, 82, 242],
 [2, 2986, 44, 82, 242, 13],
 [2, 2986, 44, 82, 242, 13, 481],
 [2, 2986, 44, 82, 242, 13, 481, 355],
 [2, 2986, 44, 82, 242, 13, 481, 355, 16],
 [2, 2986, 44, 82, 242, 13, 481, 355, 16, 2],
 [2, 2986, 44, 82, 242, 13, 481, 355, 16, 2, 372],
 [2, 2986, 44, 82, 242, 13, 481, 355, 16, 2, 372, 681],
 [2, 2986, 44, 82, 242, 13, 481, 355, 16, 2, 372, 681, 1565],
 [2, 2986, 44, 82, 242, 13, 481, 355, 16, 2, 372, 681, 1565, 9],
 [2, 2986, 44, 82, 242, 13, 481, 355, 16, 2, 372, 681, 1565, 9, 614],
 [2, 2986, 44, 82, 242, 13, 481, 355, 16, 2, 372, 681, 1565, 9, 614, 54],
 [2, 2986, 44, 82, 242, 13, 481, 355, 16, 2, 372, 681, 1565, 9, 614, 54, 13],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244,
  26],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244,
  26,
  30],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244,
  26,
  30,
  193],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244,
  26,
  30,
  193,
  264],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244,
  26,
  30,
  193,
  264,
  30],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244,
  26,
  30,
  193,
  264,
  30,
  701],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244,
  26,
  30,
  193,
  264,
  30,
  701,
  232],
 [2,
  2986,
  44,
  82,
  242,
  13,
  481,
  355,
  16,
  2,
  372,
  681,
  1565,
  9,
  614,
  54,
  13,
  171,
  341,
  244,
  26,
  30,
  193,
  264,
  30,
  701,
  232,
  10],
 [1071, 12],
 [1071, 12, 450],
 [1071, 12, 450, 41],
 [1071, 12, 450, 41, 22],
 [1071, 12, 450, 41, 22, 591],
 [1071, 12, 450, 41, 22, 591, 8],
 [1071, 12, 450, 41, 22, 591, 8, 29],
 [1071, 12, 450, 41, 22, 591, 8, 29, 4509],
 [1071, 12, 450, 41, 22, 591, 8, 29, 4509, 9782],
 [1071, 12, 450, 41, 22, 591, 8, 29, 4509, 9782, 219],
 [1071, 12, 450, 41, 22, 591, 8, 29, 4509, 9782, 219, 818],
 [1071, 12, 450, 41, 22, 591, 8, 29, 4509, 9782, 219, 818, 2222],
 [1071, 12, 450, 41, 22, 591, 8, 29, 4509, 9782, 219, 818, 2222, 3809],
 [1071, 12, 450, 41, 22, 591, 8, 29, 4509, 9782, 219, 818, 2222, 3809, 17],
 [1071, 12, 450, 41, 22, 591, 8, 29, 4509, 9782, 219, 818, 2222, 3809, 17, 54],
 [1071,
  12,
  450,
  41,
  22,
  591,
  8,
  29,
  4509,
  9782,
  219,
  818,
  2222,
  3809,
  17,
  54,
  3355],
 [1071,
  12,
  450,
  41,
  22,
  591,
  8,
  29,
  4509,
  9782,
  219,
  818,
  2222,
  3809,
  17,
  54,
  3355,
  53],
 [1071,
  12,
  450,
  41,
  22,
  591,
  8,
  29,
  4509,
  9782,
  219,
  818,
  2222,
  3809,
  17,
  54,
  3355,
  53,
  22],
 [1071,
  12,
  450,
  41,
  22,
  591,
  8,
  29,
  4509,
  9782,
  219,
  818,
  2222,
  3809,
  17,
  54,
  3355,
  53,
  22,
  416],
 [43, 66],
 [43, 66, 557],
 [43, 66, 557, 4],
 [43, 66, 557, 4, 181],
 [43, 66, 557, 4, 181, 39],
 [43, 66, 557, 4, 181, 39, 1877],
 [43, 66, 557, 4, 181, 39, 1877, 245],
 [43, 66, 557, 4, 181, 39, 1877, 245, 417],
 [43, 66, 557, 4, 181, 39, 1877, 245, 417, 418],
 [43, 66, 557, 4, 181, 39, 1877, 245, 417, 418, 159],
 [43, 66, 557, 4, 181, 39, 1877, 245, 417, 418, 159, 179],
 [43, 66, 557, 4, 181, 39, 1877, 245, 417, 418, 159, 179, 26],
 [43, 66, 557, 4, 181, 39, 1877, 245, 417, 418, 159, 179, 26, 2],
 [43, 66, 557, 4, 181, 39, 1877, 245, 417, 418, 159, 179, 26, 2, 726],
 [43, 66, 557, 4, 181, 39, 1877, 245, 417, 418, 159, 179, 26, 2, 726, 4510],
 [43, 66, 557, 4, 181, 39, 1877, 245, 417, 418, 159, 179, 26, 2, 726, 4510, 2],
 [43,
  66,
  557,
  4,
  181,
  39,
  1877,
  245,
  417,
  418,
  159,
  179,
  26,
  2,
  726,
  4510,
  2,
  45],
 [43,
  66,
  557,
  4,
  181,
  39,
  1877,
  245,
  417,
  418,
  159,
  179,
  26,
  2,
  726,
  4510,
  2,
  45,
  48],
 [43,
  66,
  557,
  4,
  181,
  39,
  1877,
  245,
  417,
  418,
  159,
  179,
  26,
  2,
  726,
  4510,
  2,
  45,
  48,
  1878],
 [7, 9783],
 [7, 9783, 327],
 [7, 9783, 327, 9784],
 [7, 9783, 327, 9784, 3810],
 [7, 9783, 327, 9784, 3810, 9785],
 [7, 9783, 327, 9784, 3810, 9785, 497],
 [7, 9783, 327, 9784, 3810, 9785, 497, 6843],
 [7, 9783, 327, 9784, 3810, 9785, 497, 6843, 14],
 [7, 9783, 327, 9784, 3810, 9785, 497, 6843, 14, 2],
 [7, 9783, 327, 9784, 3810, 9785, 497, 6843, 14, 2, 1398],
 [7, 9783, 327, 9784, 3810, 9785, 497, 6843, 14, 2, 1398, 5],
 [7, 9783, 327, 9784, 3810, 9785, 497, 6843, 14, 2, 1398, 5, 5389],
 [7, 9783, 327, 9784, 3810, 9785, 497, 6843, 14, 2, 1398, 5, 5389, 6],
 [7, 9783, 327, 9784, 3810, 9785, 497, 6843, 14, 2, 1398, 5, 5389, 6, 4511],
 [7, 9783, 327, 9784, 3810, 9785, 497, 6843, 14, 2, 1398, 5, 5389, 6, 4511, 3],
 [7,
  9783,
  327,
  9784,
  3810,
  9785,
  497,
  6843,
  14,
  2,
  1398,
  5,
  5389,
  6,
  4511,
  3,
  529],
 [7,
  9783,
  327,
  9784,
  3810,
  9785,
  497,
  6843,
  14,
  2,
  1398,
  5,
  5389,
  6,
  4511,
  3,
  529,
  4],
 [7,
  9783,
  327,
  9784,
  3810,
  9785,
  497,
  6843,
  14,
  2,
  1398,
  5,
  5389,
  6,
  4511,
  3,
  529,
  4,
  43],
 [7,
  9783,
  327,
  9784,
  3810,
  9785,
  497,
  6843,
  14,
  2,
  1398,
  5,
  5389,
  6,
  4511,
  3,
  529,
  4,
  43,
  5390],
 [7,
  9783,
  327,
  9784,
  3810,
  9785,
  497,
  6843,
  14,
  2,
  1398,
  5,
  5389,
  6,
  4511,
  3,
  529,
  4,
  43,
  5390,
  727],
 [7,
  9783,
  327,
  9784,
  3810,
  9785,
  497,
  6843,
  14,
  2,
  1398,
  5,
  5389,
  6,
  4511,
  3,
  529,
  4,
  43,
  5390,
  727,
  540],
 [88, 56],
 [88, 56, 123],
 [88, 56, 123, 91],
 [88, 56, 123, 91, 2],
 [88, 56, 123, 91, 2, 9786],
 [88, 56, 123, 91, 2, 9786, 5],
 [88, 56, 123, 91, 2, 9786, 5, 2],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728, 3],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728, 3, 2],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728, 3, 2, 45],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728, 3, 2, 45, 1024],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728, 3, 2, 45, 1024, 36],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728, 3, 2, 45, 1024, 36, 44],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728, 3, 2, 45, 1024, 36, 44, 35],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728, 3, 2, 45, 1024, 36, 44, 35, 28],
 [88, 56, 123, 91, 2, 9786, 5, 2, 144, 728, 3, 2, 45, 1024, 36, 44, 35, 28, 4],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530,
  9787],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530,
  9787,
  6844],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530,
  9787,
  6844,
  5],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530,
  9787,
  6844,
  5,
  373],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530,
  9787,
  6844,
  5,
  373,
  6],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530,
  9787,
  6844,
  5,
  373,
  6,
  78],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530,
  9787,
  6844,
  5,
  373,
  6,
  78,
  2679],
 [88,
  56,
  123,
  91,
  2,
  9786,
  5,
  2,
  144,
  728,
  3,
  2,
  45,
  1024,
  36,
  44,
  35,
  28,
  4,
  530,
  9787,
  6844,
  5,
  373,
  6,
  78,
  2679,
  309],
 [9788, 19],
 [9788, 19, 356],
 [9788, 19, 356, 220],
 [9788, 19, 356, 220, 1072],
 [9788, 19, 356, 220, 1072, 20],
 [9788, 19, 356, 220, 1072, 20, 381],
 [9788, 19, 356, 220, 1072, 20, 381, 967],
 [9788, 19, 356, 220, 1072, 20, 381, 967, 1166],
 [9788, 19, 356, 220, 1072, 20, 381, 967, 1166, 9789],
 [9788, 19, 356, 220, 1072, 20, 381, 967, 1166, 9789, 34],
 [9788, 19, 356, 220, 1072, 20, 381, 967, 1166, 9789, 34, 172],
 [9788, 19, 356, 220, 1072, 20, 381, 967, 1166, 9789, 34, 172, 3],
 [9788, 19, 356, 220, 1072, 20, 381, 967, 1166, 9789, 34, 172, 3, 250],
 [9788, 19, 356, 220, 1072, 20, 381, 967, 1166, 9789, 34, 172, 3, 250, 4],
 [9788, 19, 356, 220, 1072, 20, 381, 967, 1166, 9789, 34, 172, 3, 250, 4, 819],
 [9788,
  19,
  356,
  220,
  1072,
  20,
  381,
  967,
  1166,
  9789,
  34,
  172,
  3,
  250,
  4,
  819,
  203],
 [9788,
  19,
  356,
  220,
  1072,
  20,
  381,
  967,
  1166,
  9789,
  34,
  172,
  3,
  250,
  4,
  819,
  203,
  148],
 [9788,
  19,
  356,
  220,
  1072,
  20,
  381,
  967,
  1166,
  9789,
  34,
  172,
  3,
  250,
  4,
  819,
  203,
  148,
  76],
 [9788,
  19,
  356,
  220,
  1072,
  20,
  381,
  967,
  1166,
  9789,
  34,
  172,
  3,
  250,
  4,
  819,
  203,
  148,
  76,
  1662],
 [9788,
  19,
  356,
  220,
  1072,
  20,
  381,
  967,
  1166,
  9789,
  34,
  172,
  3,
  250,
  4,
  819,
  203,
  148,
  76,
  1662,
  16],
 [9788,
  19,
  356,
  220,
  1072,
  20,
  381,
  967,
  1166,
  9789,
  34,
  172,
  3,
  250,
  4,
  819,
  203,
  148,
  76,
  1662,
  16,
  2],
 [9788,
  19,
  356,
  220,
  1072,
  20,
  381,
  967,

In [27]:
max_len = max([len(i) for i in input_sequences])

In [28]:
max_len

44

In [29]:
input=pad_sequences(input_sequences, maxlen=max_len, padding='pre')

In [30]:
input

array([[   0,    0,    0, ...,    0,  125,  257],
       [   0,    0,    0, ...,  125,  257,   10],
       [   0,    0,    0, ...,  257,   10,   23],
       ...,
       [   0,    0,    0, ..., 7184,  865,   14],
       [   0,    0,    0, ...,  865,   14,   79],
       [   0,    0,    0, ...,   14,   79,  956]],
      shape=(170627, 44), dtype=int32)

In [31]:
X=input[:,:-1]
y=input[:,-1]

In [32]:
X[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 125], dtype=int32)

In [33]:
X.shape

(170627, 43)

In [34]:
y.shape

(170627,)

In [42]:
y=np.array(y)

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [39]:
X_train.shape

(136501, 43)

In [40]:
vocab_size = len(tokenizer.word_index) + 1

In [41]:
vocab_size

19734

In [43]:
max_len=X.shape[1]

In [44]:
max_len

43

In [46]:
model = Sequential([
    Embedding(vocab_size, 128, input_length=max_len),
    LSTM(256),
    Dense(vocab_size, activation='softmax')
])

c:\Users\harsh\OneDrive\Desktop\Gen AI\Deep Learning\LSTM\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [47]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [49]:
model.build(input_shape=(None, max_len))

In [50]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 43, 128)        │     2,525,952 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 19734)          │     5,071,638 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,991,830 (30.49 MB)

 Trainable params: 7,991,830 (30.49 MB)

 Non-trainable params: 0 (0.00 B)

In [52]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
4266/4266 ━━━━━━━━━━━━━━━━━━━━ 810s 190ms/step - accuracy: 0.0783 - loss: 7.3938 - val_accuracy: 0.1032 - val_loss: 7.0571
Epoch 2/10
3876/4266 ━━━━━━━━━━━━━━━━━━━━ 1:09 178ms/step - accuracy: 0.1168 - loss: 6.5357

KeyboardInterrupt:

In [ ]:
model.save('lstm_model.h5')

In [ ]:
import pickle
with open('tokenizer.pickle', 'wb') as file:
    pickle.dump(tokenizer, file)